### ISSUE TITLE
ERR_INVALID_ARG_TYPE: The "original" argument must be of type function. Received undefined

### ISSUE THREAD

**Issue by jamesottaway** [devcontainers/cli#162]
I'm trying to use this CLI w/ an old project stuck on Node v14.3, which blew up spectacularly.

```
❯ fnm exec --using=14.3 -- npx @devcontainers/cli --version
internal/util.js:279
    throw new ERR_INVALID_ARG_TYPE('original', 'Function', original);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "original" argument must be of type function. Received undefined
    at promisify (internal/util.js:279:11)
    at Object.<anonymous> (/Users/james.ottaway/.npm/_npx/c5e74fa377e9cf23/node_modules/@devcontainers/cli/dist/spec-utils/pfs.js:47:40)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
    at Object.<anonymous> (/Users/james.ottaway/.npm/_npx/c5e74fa377e9cf23/node_modules/@devcontainers/cli/dist/spec-common/commonUtils.js:33:15)
    at Module._compile (internal/modules/cjs/loader.js:1200:30) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

I managed to work out that the earliest minor version under Node 14 that works is v14.14:

```
❯ fnm exec --using=14.13 -- npx @devcontainers/cli --version
The "original" argument must be of type function. Received undefined

❯ fnm exec --using=14.14 -- npx @devcontainers/cli --version
0.14.2
```

Probably just needs a strict engine version specified in the `package.json`.

**Comment by chrmarti** [comment]
Good catch, we use `fs.rm` and that was only added in Node.js 14.14.0. Fixing the required version.
