### ISSUE TITLE
`devcontainer features package` fails when `devcontainer-feature.json` contains comments

### ISSUE THREAD

**Issue by snebjorn** [devcontainers/cli#214]
fails when **devcontainer-feature.json** contains comments.
```
SyntaxError: Unexpected token / in JSON at position 274
    at JSON.parse (<anonymous>)
    at packageCollection (/usr/local/lib/node_modules/@devcontainers/cli/dist/spec-node/collectionCommonUtils/packageCommandImpl.js:[17](https://github.com/snebjorn/devcontainer-feature/actions/runs/3211796200/jobs/5250216647#step:3:18)7:35)
    at async packageFeatureCollection (/usr/local/lib/node_modules/@devcontainers/cli/dist/spec-node/featuresCLI/packageCommandImpl.js:49:12)
    at async doFeaturesPackageCommand (/usr/local/lib/node_modules/@devcontainers/cli/dist/spec-node/featuresCLI/packageCommandImpl.js:26:26)
    at async featuresPublish (/usr/local/lib/node_modules/@devcontainers/cli/dist/spec-node/featuresCLI/publish.js:72:22)
    at async /usr/local/lib/node_modules/@devcontainers/cli/dist/spec-node/featuresCLI/publish.js:45:[18](https://github.com/snebjorn/devcontainer-feature/actions/runs/3211796200/jobs/5250216647#step:3:19)
```

**Comment by joshspicer** [comment]
https://github.com/devcontainers/action/issues/75
