### ISSUE TITLE
connect ETIMEDOUT 185.199.111.154:443 when downloading a feature

### ISSUE THREAD

**Issue by Chuxel** [devcontainers/cli#281]
From @dsyer https://github.com/devcontainers/features/pull/228?notification_referrer_id=NT_kwDOAATDvLE0NjMzNjA2MTgzOjMxMjI1Mg#issuecomment-1311613770

There appears to potentially be some sort of networking issue going on.  Possibily with GHCR?  //cc @jkeech @edgonmsft @samruddhikhandale @joshspicer 

-----

Can someone help with some more detailed instructions on how to use this? I tried adding the feature and getting a lot of errors. Different errors, no obvious pattern. This one is common:

```
[2022-11-11T11:59:37.210Z] Start: Run: tar --no-same-owner -x -f -
[2022-11-11T11:59:37.228Z] Stop (18 ms): Run: tar --no-same-owner -x -f -
[2022-11-11T11:59:37.237Z] * Processing feature: ghcr.io/devcontainers/features/nix
[2022-11-11T11:59:37.744Z] * Processing feature: ghcr.io/devcontainers/features/docker-in-docker
[2022-11-11T11:59:38.329Z] * Fetching feature: nix_1_oci
[2022-11-11T12:01:48.847Z] error: Error: connect ETIMEDOUT 185.199.111.154:443
[2022-11-11T12:01:48.847Z] (!) ERR: Failed to fetch feature: Failed to download package for ghcr.io/devcontainers/features/nix 
[2022-11-11T12:01:48.849Z] Error: Failed to download package for ghcr.io/devcontainers/features/nix
[2022-11-11T12:01:48.850Z]     at vw (/home/dsyer/.vscode/extensions/ms-vscode-remote.remote-containers-0.247.0/dist/spec-node/devContainersSpecCLI.js:155:6485)
[2022-11-11T12:01:48.850Z]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[2022-11-11T12:01:48.850Z]     at async yS (/home/dsyer/.vscode/extensions/ms-vscode-remote.remote-containers-0.247.0/dist/spec-node/devContainersSpecCLI.js:186:6943)
[2022-11-11T12:01:48.851Z]     at async na (/home/dsyer/.vscode/extensions/ms-vscode-remote.remote-containers-0.247.0/dist/spec-node/devContainersSpecCLI.js:186:2444)
[2022-11-11T12:01:48.851Z]     at async oo (/home/dsyer/.vscode/extensions/ms-vscode-remote.remote-containers-0.247.0/dist/spec-node/devContainersSpecCLI.js:186:12686)
[2022-11-11T12:01:48.852Z]     at async sa (/home/dsyer/.vscode/extensions/ms-vscode-remote.remote-containers-0.247.0/dist/spec-node/devContainersSpecCLI.js:186:11651)
[2022-11-11T12:01:48.852Z]     at async bu (/home/dsyer/.vscode/extensions/ms-vscode-remote.remote-containers-0.247.0/dist/spec-node/devContainersSpecCLI.js:254:2847)
[2022-11-11T12:01:48.852Z]     at async Jw (/home/dsyer/.vscode/extensions/ms-vscode-remote.remote-containers-0.247.0/dist/spec-node/devContainersSpecCLI.js:254:1779)
[2022-11-11T12:01:48.853Z]     at async JS (/home/dsyer/.vscode/extensions/ms-vscode-remote.remote-containers-0.247.0/dist/spec-node/devContainersSpecCLI.js:260:2006)
[2022-11-11T12:01:48.853Z]     at async co (/home/dsyer/.vscode/extensions/ms-vscode-remote.remote-containers-0.247.0/dist/spec-node/devContainersSpecCLI.js:260:3110)
[2022-11-11T12:01:48.857Z] Stop (131867 ms): Run: /nix/store/nrdmbm43k7xyc9nvg741zcqpi7i72rvn-vscode-1.70.2/lib/vscode/code /home/dsyer/.vscode/extensions/ms-vscode-remote.remote-containers-0.247.0/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /home/dsyer/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --workspace-folder /home/dsyer/dev/scratch/hello-as --workspace-mount-consistency cached --id-label devcontainer.local_folder=/home/dsyer/dev/scratch/hello-as --log-level debug --log-format json --config /home/dsyer/dev/scratch/hello-as/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2022-11-11T12:01:48.858Z] Exit code 1
[2022-11-11T12:01:48.871Z] Command failed: /nix/store/nrdmbm43k7xyc9nvg741zcqpi7i72rvn-vscode-1.70.2/lib/vscode/code /home/dsyer/.vscode/extensions/ms-vscode-remote.remote-containers-0.247.0/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /home/dsyer/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --workspace-folder /home/dsyer/dev/scratch/hello-as --workspace-mount-consistency cached --id-label devcontainer.local_folder=/home/dsyer/dev/scratch/hello-as --log-level debug --log-format json --config /home/dsyer/dev/scratch/hello-as/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2022-11-11T12:01:48.871Z] Exit code 1
```

---

From @Chuxel 

@dsyer Would you mind raising an issue with your specifics?  In particular the base image you are using, OS, architecture, etc.  Possible there's a scenario where things are not working as expected. That particular error though sounds like its actually having a hard time downloading the feature itself which could be connectivity related. #275 is very specific to the universal image, for example.

---

From @dsyer

That's it really, for the specifics. The JSON is just the default if you add ubuntu and nix. My network connectivity is generally good here locally. Maybe there was a DNS glitch out there somewhere? 185.199.111.154 looks like Github (not gcr.io).

**Comment by Chuxel** [comment]
@dsyer Are you behind a proxy at all? Very odd.

**Comment by dsyer** [comment]
No proxy here. It definitely was intermittent. I eventually got it to work, but it still fails sometimes.

**Comment by dsyer** [comment]
Here's a complete log if it helps. This happens about 90% of the time to me.

```
[2022-11-13T17:14:41.371Z] Dev Containers 0.263.0 in VS Code 1.73.1 (6261075646f055b99068d3688932416f2346dd3b).
[2022-11-13T17:14:41.371Z] Start: Resolving Remote
[2022-11-13T17:14:41.377Z] Setting up container for folder or workspace: /home/dsyer/dev/scratch/hello-as
[2022-11-13T17:14:41.384Z] Start: Check Docker is running
[2022-11-13T17:14:41.384Z] Start: Run: docker version --format {{.Server.APIVersion}}
[2022-11-13T17:14:41.426Z] Stop (42 ms): Run: docker version --format {{.Server.APIVersion}}
[2022-11-13T17:14:41.427Z] Server API version: 1.41
[2022-11-13T17:14:41.427Z] Stop (43 ms): Check Docker is running
[2022-11-13T17:14:41.427Z] Start: Run: docker volume ls -q
[2022-11-13T17:14:41.458Z] Stop (31 ms): Run: docker volume ls -q
[2022-11-13T17:14:41.464Z] Start: Run: docker ps -q -a --filter label=vsch.local.folder=/home/dsyer/dev/scratch/hello-as --filter label=vsch.quality=stable
[2022-11-13T17:14:41.494Z] Stop (30 ms): Run: docker ps -q -a --filter label=vsch.local.folder=/home/dsyer/dev/scratch/hello-as --filter label=vsch.quality=stable
[2022-11-13T17:14:41.494Z] Start: Run: /nix/store/0clacs5vkmcns9p5fi3b7kbiix6mqwjk-vscode-1.73.1/lib/vscode/code --ms-enable-electron-run-as-node /home/dsyer/.vscode/extensions/ms-vscode-remote.remote-containers-0.263.0/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /home/dsyer/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --workspace-folder /home/dsyer/dev/scratch/hello-as --workspace-mount-consistency cached --id-label devcontainer.local_folder=/home/dsyer/dev/scratch/hello-as --log-level debug --log-format json --config /home/dsyer/dev/scratch/hello-as/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --remove-existing-container --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2022-11-13T17:14:41.756Z] (node:3443815) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
[2022-11-13T17:14:41.756Z] (Use `code --trace-deprecation ...` to show where the warning was created)
[2022-11-13T17:14:41.758Z] @devcontainers/cli 0.23.2. Node.js v16.14.2. linux 5.4.0-125-generic x64.
[2022-11-13T17:14:41.758Z] Start: Run: docker buildx version
[2022-11-13T17:14:41.824Z] Stop (66 ms): Run: docker buildx version
[2022-11-13T17:14:41.825Z] 
[2022-11-13T17:14:41.825Z] docker: 'buildx' is not a docker command.
See 'docker --help'

[2022-11-13T17:14:41.826Z] Exit code 1
[2022-11-13T17:14:41.826Z] Start: Resolving Remote
[2022-11-13T17:14:41.831Z] Start: Run: git rev-parse --show-cdup
[2022-11-13T17:14:41.838Z] Stop (7 ms): Run: git rev-parse --show-cdup
[2022-11-13T17:14:41.840Z] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/home/dsyer/dev/scratch/hello-as
[2022-11-13T17:14:41.900Z] Stop (60 ms): Run: docker ps -q -a --filter label=devcontainer.local_folder=/home/dsyer/dev/scratch/hello-as
[2022-11-13T17:14:41.901Z] Start: Run: docker inspect --type image mcr.microsoft.com/devcontainers/base:ubuntu
[2022-11-13T17:14:41.938Z] Stop (37 ms): Run: docker inspect --type image mcr.microsoft.com/devcontainers/base:ubuntu
[2022-11-13T17:14:41.939Z] local container features stored at: /home/dsyer/.vscode/extensions/ms-vscode-remote.remote-containers-0.263.0/dist/node_modules/vscode-dev-containers/container-features
[2022-11-13T17:14:41.940Z] Start: Run: tar --no-same-owner -x -f -
[2022-11-13T17:14:41.956Z] Stop (16 ms): Run: tar --no-same-owner -x -f -
[2022-11-13T17:14:41.963Z] * Processing feature: ghcr.io/devcontainers/features/nix:1
[2022-11-13T17:14:42.413Z] * Processing feature: ghcr.io/devcontainers/features/docker-in-docker:1
[2022-11-13T17:14:42.877Z] * Fetching feature: nix_1_oci
[2022-11-13T17:16:53.931Z] error: Error: connect ETIMEDOUT 185.199.111.154:443
[2022-11-13T17:16:53.931Z] (!) ERR: Failed to fetch feature: Failed to download package for ghcr.io/devcontainers/features/nix 
[2022-11-13T17:16:53.933Z] Error: Failed to download package for ghcr.io/devcontainers/features/nix
[2022-11-13T17:16:53.934Z]     at fO (/home/dsyer/.vscode/extensions/ms-vscode-remote.remote-containers-0.263.0/dist/spec-node/devContainersSpecCLI.js:1736:10509)
[2022-11-13T17:16:53.934Z]     at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
[2022-11-13T17:16:53.935Z]     at async xse (/home/dsyer/.vscode/extensions/ms-vscode-remote.remote-containers-0.263.0/dist/spec-node/devContainersSpecCLI.js:1804:8294)
[2022-11-13T17:16:53.935Z]     at async bm (/home/dsyer/.vscode/extensions/ms-vscode-remote.remote-containers-0.263.0/dist/spec-node/devContainersSpecCLI.js:1804:2465)
[2022-11-13T17:16:53.935Z]     at async Gf (/home/dsyer/.vscode/extensions/ms-vscode-remote.remote-containers-0.263.0/dist/spec-node/devContainersSpecCLI.js:1806:1327)
[2022-11-13T17:16:53.936Z]     at async _m (/home/dsyer/.vscode/extensions/ms-vscode-remote.remote-containers-0.263.0/dist/spec-node/devContainersSpecCLI.js:1806:306)
[2022-11-13T17:16:53.936Z]     at async pF (/home/dsyer/.vscode/extensions/ms-vscode-remote.remote-containers-0.263.0/dist/spec-node/devContainersSpecCLI.js:1887:2022)
[2022-11-13T17:16:53.937Z]     at async eT (/home/dsyer/.vscode/extensions/ms-vscode-remote.remote-containers-0.263.0/dist/spec-node/devContainersSpecCLI.js:1887:901)
[2022-11-13T17:16:53.937Z]     at async voe (/home/dsyer/.vscode/extensions/ms-vscode-remote.remote-containers-0.263.0/dist/spec-node/devContainersSpecCLI.js:1893:2049)
[2022-11-13T17:16:53.937Z]     at async Xf (/home/dsyer/.vscode/extensions/ms-vscode-remote.remote-containers-0.263.0/dist/spec-node/devContainersSpecCLI.js:1893:3212)
[2022-11-13T17:16:53.942Z] Stop (132448 ms): Run: /nix/store/0clacs5vkmcns9p5fi3b7kbiix6mqwjk-vscode-1.73.1/lib/vscode/code --ms-enable-electron-run-as-node /home/dsyer/.vscode/extensions/ms-vscode-remote.remote-containers-0.263.0/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /home/dsyer/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --workspace-folder /home/dsyer/dev/scratch/hello-as --workspace-mount-consistency cached --id-label devcontainer.local_folder=/home/dsyer/dev/scratch/hello-as --log-level debug --log-format json --config /home/dsyer/dev/scratch/hello-as/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --remove-existing-container --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2022-11-13T17:16:53.943Z] Exit code 1
[2022-11-13T17:16:53.957Z] Command failed: /nix/store/0clacs5vkmcns9p5fi3b7kbiix6mqwjk-vscode-1.73.1/lib/vscode/code --ms-enable-electron-run-as-node /home/dsyer/.vscode/extensions/ms-vscode-remote.remote-containers-0.263.0/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /home/dsyer/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --workspace-folder /home/dsyer/dev/scratch/hello-as --workspace-mount-consistency cached --id-label devcontainer.local_folder=/home/dsyer/dev/scratch/hello-as --log-level debug --log-format json --config /home/dsyer/dev/scratch/hello-as/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --remove-existing-container --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2022-11-13T17:16:53.958Z] Exit code 1
```

**Comment by dsyer** [comment]
Maybe this is the wrong place to ask, but why not use a base image (which is then properly cached) for nix and docker etc. (things that are extracted into "features" in devcontainers)? "Features" take a long time to install, delaying startup of the devcontainer. And then they fail 90% of the time (right now for me anyway).

**Comment by Chuxel** [comment]
We maintain [quite a few base images already](https://github.com/devcontainers/images). Features are about enabling arbitrary ecosystems or adding "one more thing."

We need to track down why you are experiencing this problem. All of our base images use Features so it's unclear why you're experiencing this while others are not.

**Comment by Chuxel** [comment]
Quick follow up - where are you located?  It could be geo specific.

**Comment by dsyer** [comment]
> Quick follow up - where are you located?

UK.  185.199.111.154 is indeed unreachable. But why is it even trying?

**Comment by dsyer** [comment]
I don't know if it helps but I seem to have more chance of success if I `docker system prune` on the host first.

**Comment by joshspicer** [comment]
Hey, @dsyer - Can you run the debug steps at http://github-debug.com/ and email me the results (`<my-username>@github.com`).  I'm working with the GitHub networking team to understand this better.

**Comment by dsyer** [comment]
Sure. I'm travelling this week, so I'll come back to this on Friday (or maybe Monday) when I'm back.

**Comment by Chuxel** [comment]
@dsyer Thanks - it does look like something may be up with githubusercontent.com in you region so thank you for bringing this to our attention.

**Comment by julien-blanchon** [comment]
Same error in France

**Comment by Chuxel** [comment]
@julien-blanchon Can you follow the directions above? https://github.com/devcontainers/cli/issues/281#issuecomment-1315780325

The networking team needs data to debug.

**Comment by artemklevtsov** [comment]
The same with 185.199.109.154:443.

**Comment by NaMLZo** [comment]
The same with 198.51.44.1:443

**Comment by BramStevensCegeka** [comment]
Same issue as well with  140.82.121.33:443

**Comment by materod-upv** [comment]
Same issue as well with  140.82.121.33:443

**Comment by franzbischoff** [comment]
Today its me with 140.82.121.33:443
no clue

**Comment by suharnikov** [comment]
Oh, I found this club :smile: 
Today I got the same error:
https://github.com/microsoft/vscode-remote-release/issues/9102

**Comment by ani1797** [comment]
Same issue here today with 2606:50c0:8003::154:443

**Comment by suharnikov** [comment]
> Same issue here today with 2606:50c0:8003::154:443

I just restart my router, and it works again. I'm not sure what happened

**Comment by franzbischoff** [comment]
I did nothing and it worked again. I think the "timeout" may be a real "timeout": the server must be overloaded.

**Comment by ani1797** [comment]
Yeah it might be couple of their servers being overloaded and we ended up with a slower server. I tried the same exact thing on a codespace and no issues there(maybe due to the caching they implemented?). Local had the issue for a while and resolved itself this morning but now same issue.

**Comment by datawagner** [comment]
I've solved it by connecting through 4g on my phone and downloading again.

**Comment by DgeGagTelus** [comment]
I'm experiencing this on a remote-ssh host behind a proxy. Any idea ? Any additional config required to support proxy on remote-ssh (I already have the http(s)_proxy env vars setupped) ? 

Everything else seems to work fine.

**Comment by DgeGagTelus** [comment]
@joshspicer , I tested a bit more and I can confirm that building a devcontainer behind a proxy without using "features" works fine. As soon as I had a feature (eg.: git), then I get the ETIMEDOUT error for that feature. Should I open a new issue ?

**Comment by eknowles** [comment]
Adding my solution, I was getting these timeouts even after using cloudfront DNS, I got this issue when moving to a different wifi network with a different ISP.

My solution was to switch off from Cloudflares DNS to the ISP default and it worked.

My suggestion to others is the same.

either flush dns
```shell
sudo dscacheutil -flushcache; sudo killall -HUP mDNSResponder
```
or switch to cloudflare dns if you prefer https://one.one.one.one/
