### ISSUE TITLE
Error: connect ETIMEDOUT 185.199.108.154:443 when downloading a feature

### ISSUE THREAD

**Issue by rtalwar2** [devcontainers/cli#323]
There appears to be a networking issue going on with the GitHub network. I have a similar issue like [this one](https://github.com/devcontainers/cli/issues/281)

```
[847367 ms] Start: Run in Host: docker version --format {{.Server.APIVersion}}
[847549 ms] 1.41
[848560 ms] Start: Run in Host: /home/rtalwar/.vscode-server/bin/5235c6bb189b60b01b1f49062f4ffa42384f8c91/node /home/rtalwar/.vscode-remote-containers/dist/dev-containers-cli-0.266.1/dist/spec-node/devContainersSpecCLI.js read-configuration --workspace-folder /home/rtalwar/sysdesign-2022-project-group-5 --log-level debug --log-format json --config /home/rtalwar/sysdesign-2022-project-group-5/.devcontainer/devcontainer.json --include-merged-configuration --mount-workspace-git-root true --terminal-columns 112 --terminal-rows 18
[849041 ms] (node:2804660) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
[849042 ms] (Use `node --trace-deprecation ...` to show where the warning was created)
[848290 ms] @devcontainers/cli 0.25.2. Node.js v16.14.2. linux 5.4.0-67-generic x64.
[848290 ms] Start: Run: git rev-parse --show-cdup
[848301 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/home/rtalwar/sysdesign-2022-project-group-5
[848353 ms] * Processing feature: git
[848353 ms] (!) WARNING: Using the deprecated 'git' Feature. See https://github.com/devcontainers/features/tree/main/src/git#example-usage for the updated Feature.
[848775 ms] * Processing feature: ghcr.io/devcontainers/features/docker-in-docker:1
[849160 ms] * Processing feature: ghcr.io/devcontainers/features/java:1
[849543 ms] * Fetching feature: git_1_oci
[980743 ms] error: Error: connect ETIMEDOUT 185.199.108.154:443
[980744 ms] (!) ERR: Failed to fetch feature: Failed to download package for ghcr.io/devcontainers/features/git 
[980744 ms] Error: Failed to download package for ghcr.io/devcontainers/features/git
    at EO (/home/rtalwar/.vscode-remote-containers/dist/dev-containers-cli-0.266.1/dist/spec-node/devContainersSpecCLI.js:1737:11441)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Nse (/home/rtalwar/.vscode-remote-containers/dist/dev-containers-cli-0.266.1/dist/spec-node/devContainersSpecCLI.js:1805:8292)
    at async Sm (/home/rtalwar/.vscode-remote-containers/dist/dev-containers-cli-0.266.1/dist/spec-node/devContainersSpecCLI.js:1805:2465)
    at async Cue (/home/rtalwar/.vscode-remote-containers/dist/dev-containers-cli-0.266.1/dist/spec-node/devContainersSpecCLI.js:2020:31937)
[981494 ms] Exit code 1
```

**Comment by rtalwar2** [comment]
Network issue solved on it's own.
