### ISSUE TITLE
bug: Cannot recognise bash-style arguments in Dockerfile

### ISSUE THREAD

**Issue by ShauryaAg** [devcontainers/cli#336]
devcontainer cli is unable to parse bash-style arguments, that is, arguments of type `${arg1:+"something"}`

For example:
When using the below `Dockerfile` 
```Dockerfile
ARG cloud
FROM ${cloud:+"my.ecr.repo/"}myimage:tag
```

The output after parsing should be, if the value `cloud` ARG is set:
```Dockerfile
FROM my.exr.repo/myimage:tag
```
and otherwise should be:
```Dockerfile
FROM myimage:tag
```

However, 
`devcontainer` cli throws an error that it cannot parse the above mentioned `Dockerfile`
```
[11 ms] @devcontainers/cli 0.25.2. Node.js v16.14.2. darwin 21.2.0 arm64.
[469 ms] Parsed version '+' for input 'docker.io/library/1:+' failed validation.
Error: Command failed: docker inspect --type image 1:+
    at Aoe (/Users/shaurya/.vscode/extensions/ms-vscode-remote.remote-containers-0.266.1/dist/spec-node/devContainersSpecCLI.js:70182:9)
    at uT (/Users/shaurya/.vscode/extensions/ms-vscode-remote.remote-containers-0.266.1/dist/spec-node/devContainersSpecCLI.js:70175:11)
    at async Poe (/Users/shaurya/.vscode/extensions/ms-vscode-remote.remote-containers-0.266.1/dist/spec-node/devContainersSpecCLI.js:70543:34)
    at async Zf (/Users/shaurya/.vscode/extensions/ms-vscode-remote.remote-containers-0.266.1/dist/spec-node/devContainersSpecCLI.js:70597:9)
    at async aue (/Users/shaurya/.vscode/extensions/ms-vscode-remote.remote-containers-0.266.1/dist/spec-node/devContainersSpecCLI.js:72760:13)
    at async oue (/Users/shaurya/.vscode/extensions/ms-vscode-remote.remote-containers-0.266.1/dist/spec-node/devContainersSpecCLI.js:72747:9)
{"outcome":"error","message":"Command failed: docker inspect --type image 1:+","description":"An error occurred setting up the container."}
```

In the above run, the value of `cloud` argument was set to `1`, hence it outputted `1:+`, which is not the expected result.

devcontainer cli version: 0.25.2

Reference:
- https://docs.docker.com/engine/reference/builder/#environment-replacement

**Comment by ShauryaAg** [comment]
Hey, @joshspicer I have submitted a PR for the reported issue, could you please review it?
