### ISSUE TITLE
Devcontainers start fails with docker-compose

### ISSUE THREAD

**Issue by drodil** [devcontainers/cli#371]
I have .devcontainer/devcontainer.json as follows:

```json
{
  "dockerComposeFile": "../docker-compose-devcontainer.yaml",
  "service": "devcontainer",
  "workspaceFolder": "/workspace",
  "shutdownAction": "stopCompose"
}
```

And ./docker-compose-devcontainer.yaml:

```yaml
version: '3.9'
services:
  psql:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
```

When trying to start the devcontainer from CLI (or from VSCode) I get the following error:

```sh
[68 ms] @devcontainers/cli 0.27.1. Node.js v16.17.0. darwin 22.1.0 x64.
Error: Command failed: docker-compose -f /myfolder/docker-compose-devcontainer.yaml --profile * config
    at vc (/myfolder/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:1856:867)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async zne (/myfolder/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:1822:1370)
    at async Wne (/myfolder/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:1804:2396)
    at async die (/myfolder/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:1871:2266)
    at async qf (/myfolder/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:1871:3239)
    at async Gse (/myfolder/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:1995:16367)
    at async Hse (/myfolder/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:1995:16121)
{"outcome":"error","message":"Command failed: docker-compose -f /myfolder/docker-compose-devcontainer.yaml --profile * config","description":"An error occurred retrieving the Docker Compose configuration.","containerId":"d577666fd2416c5272ccabafa890974b4c9f549bc22c88d2b88d2ce54939a5b1"}
```

Running just the docker-compose command will for some reason just print the help of docker-compose command:

```sh
$ docker-compose -f docker-compose-devcontainer.yaml --profile * config

Usage:  docker compose [OPTIONS] COMMAND

...[default docker-compose --help output here]

Run 'docker compose COMMAND --help' for more information on a command.
unknown docker command: "compose README.md"
```

Docker Compose version v2.13.0
Devcontainers CLI version  0.27.1

Running the docker-compose command without `--profile *` flag works fine. What could be the issue? Can I remove the `--profile` flag from devcontainers command somehow?

**Comment by drodil** [comment]
The flag is added here: 
https://github.com/devcontainers/cli/blob/b57f29e277c0f229324f08397a7e996a0e4e09f5/src/spec-node/dockerCompose.ts#L560

**Comment by kierans** [comment]
> Sorry, my mistake. A typo.

What was the typo? I'm facing similar issues.
