### ISSUE TITLE
npm install command requires Python 2, fails on Python 3-only installs

### ISSUE THREAD

**Issue by kyanha** [devcontainers/cli#389]
Python 2 has been deprecated for close to a decade. Can it just die already? Please?

Please change the NPM package to use Python 3 syntax instead of Python 2.

```
D:\work\devcontainers\cli>npm install -g @devcontainers/cli
C:\Users\user\AppData\Roaming\npm\devcontainer -> C:\Users\user\AppData\Roaming\npm\node_modules\@devcontainers\cli\devcontainer.js

> node-pty@0.10.1 install C:\Users\user\AppData\Roaming\npm\node_modules\@devcontainers\cli\node_modules\node-pty
> node scripts/install.js


C:\Users\user\AppData\Roaming\npm\node_modules\@devcontainers\cli\node_modules\node-pty>if not defined npm_config_node_gyp (node "D:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "D:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Python3\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gyp ERR! stack SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:294:12)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:982:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
gyp ERR! System Windows_NT 10.0.19045
gyp ERR! command "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\user\AppData\Roaming\npm\node_modules\@devcontainers\cli\node_modules\node-pty
gyp ERR! node -v v10.16.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-pty@0.10.1 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-pty@0.10.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\AppData\Roaming\npm-cache\_logs\2023-01-31T15_10_36_577Z-debug.log
```

**Comment by chrmarti** [comment]
The log shows NodeJS is at v10.16.1, please upgrade to v14.14.0 or later. That should also bring in a more recent version of node-gyp which I suspect is the source of the error.
