### ISSUE TITLE
Docker v23 on linux causes devcontainer dockerfile to fail with eof

### ISSUE THREAD

**Issue by nickbabcock** [devcontainers/cli#398]
I have a pretty simple setup

**.devcontainer/devcontainer.json**
```json
{
  "build": {
    "dockerfile": "Dockerfile"
  }
}
```

**.devcontainer/Dockerfile**
```dockerfile
FROM mcr.microsoft.com/devcontainers/base:debian
```

When I execute:

```bash
devcontainer build --workspace-folder .
```

It fails with:

```
[8 ms] @devcontainers/cli 0.29.0. Node.js v18.12.1. linux 5.15.0-58-generic x64.
[131 ms] Start: Run: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /tmp/devcontainercli-nick/container-features/0.29.0-1675436665362/Dockerfile-with-features -t vsc-pdx-tools-c6e30ed9b67aad39ca1d11866a63d38e --target dev_containers_target_stage --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label /home/nick/projects/pdx-tools/.devcontainer
[+] Building 0.1s (4/5)                                                         
 => [internal] load .dockerignore                                          0.0s
 => => transferring context: 2B                                            0.0s
 => [internal] load build definition from Dockerfile-with-features         0.1s
 => => transferring dockerfile: 433B                                       0.0s
 => [internal] load metadata for mcr.microsoft.com/devcontainers/base:deb  0.0s
 => CACHED [dev_container_auto_added_stage_label 1/1] FROM mcr.microsoft.  0.0s
 => preparing layers for inline cache                                      0.1s
ERROR: failed to receive status: rpc error: code = Unavailable desc = error reading from server: EOF
Error: Command failed: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /tmp/devcontainercli-nick/container-features/0.29.0-1675436665362/Dockerfile-with-features -t vsc-pdx-tools-c6e30ed9b67aad39ca1d11866a63d38e --target dev_containers_target_stage --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label /home/nick/projects/pdx-tools/.devcontainer
    at pie (/home/nick/.volta/tools/image/packages/@devcontainers/cli/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:1916:1698)
    at async vF (/home/nick/.volta/tools/image/packages/@devcontainers/cli/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:1915:1972)
    at async uoe (/home/nick/.volta/tools/image/packages/@devcontainers/cli/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:2045:26894)
    at async aoe (/home/nick/.volta/tools/image/packages/@devcontainers/cli/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:2045:25017)
{"outcome":"error","message":"Command failed: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /tmp/devcontainercli-nick/container-features/0.29.0-1675436665362/Dockerfile-with-features -t vsc-pdx-tools-c6e30ed9b67aad39ca1d11866a63d38e --target dev_containers_target_stage --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label /home/nick/projects/pdx-tools/.devcontainer","description":"An error occurred building the image."}
```

I'm assuming this has something to do with Docker v23 (released a couple days ago) making buildkit the default on linux.

I'm happy to provide more info about my environment if that'll help -- or if there is a better repo to report this issue.

**Comment by mrjackwills** [comment]
I posted in another issue, https://github.com/microsoft/vscode-remote-release/issues/6814#issuecomment-1416245446, but have a temporary solution

**Comment by chrmarti** [comment]
We got an answer in docker buildx project, a fix is in the pipe: https://github.com/docker/buildx/issues/1325#issuecomment-1416444770

_Originally posted by @jaudiger in https://github.com/microsoft/vscode-remote-release/issues/7958#issuecomment-1416495001_
