### ISSUE TITLE
Error response from daemon: dockerfile parse error line 1: unknown instruction: .DOCKERIGNORE

### ISSUE THREAD

**Issue by will3g** [devcontainers/cli#420]
Hi guys,

When I execute any dev container in my Visual Studio Code, I have this problem. Can someone help me?

PS: I'm using ubuntu 22.04

**Log:**
![image](https://user-images.githubusercontent.com/49616761/220429219-958291a7-ad91-408e-8ca3-f95fa5d39f5f.png)

```
[35 ms] Dev Containers 0.280.0 in VS Code 1.75.1 (441438abd1ac652551dbe4d408dfcec8a499b8bf).
[35 ms] Start: Resolving Remote
[85 ms] Setting up container for folder or workspace: /home/edglobo/Desktop/container/projects/curso/3-modulo-comunicao-entre-sistemas/laminas
[87 ms] Start: Check Docker is running
[87 ms] Start: Run: docker version --format {{.Server.APIVersion}}
[114 ms] Server API version: 1.41
[115 ms] Start: Run: docker volume ls -q
[131 ms] Start: Run: docker ps -q -a --filter label=vsch.local.folder=/home/edglobo/Desktop/container/projects/curso/3-modulo-comunicao-entre-sistemas/laminas --filter label=vsch.quality=stable
[147 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/home/edglobo/Desktop/container/projects/curso/3-modulo-comunicao-entre-sistemas/laminas --filter label=devcontainer.config_file=/home/edglobo/Desktop/container/projects/curso/3-modulo-comunicao-entre-sistemas/laminas/.devcontainer/devcontainer.json
[200 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/home/edglobo/Desktop/container/projects/curso/3-modulo-comunicao-entre-sistemas/laminas
[218 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/home/edglobo/Desktop/container/projects/curso/3-modulo-comunicao-entre-sistemas/laminas
[236 ms] Start: Run: /usr/share/code/code --ms-enable-electron-run-as-node /home/edglobo/.vscode/extensions/ms-vscode-remote.remote-containers-0.280.0/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /home/edglobo/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --container-session-data-folder /tmp/devcontainers-4addaaa8-00d6-4643-8466-388d0a2cad531677004129745 --workspace-folder /home/edglobo/Desktop/container/projects/curso/3-modulo-comunicao-entre-sistemas/laminas --workspace-mount-consistency cached --id-label devcontainer.local_folder=/home/edglobo/Desktop/container/projects/curso/3-modulo-comunicao-entre-sistemas/laminas --id-label devcontainer.config_file=/home/edglobo/Desktop/container/projects/curso/3-modulo-comunicao-entre-sistemas/laminas/.devcontainer/devcontainer.json --log-level debug --log-format json --config /home/edglobo/Desktop/container/projects/curso/3-modulo-comunicao-entre-sistemas/laminas/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[453 ms] (node:2449943) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
[453 ms] (Use `code --trace-deprecation ...` to show where the warning was created)
[454 ms] @devcontainers/cli 0.31.0. Node.js v16.14.2. linux 5.15.0-58-generic x64.
[454 ms] Start: Run: docker buildx version
[505 ms] github.com/docker/buildx v0.10.0-docker 876462897612d36679153c3414f7689626251501
[505 ms] 
[505 ms] Start: Resolving Remote
[509 ms] Start: Run: docker-compose version --short
[513 ms] Start: Run: docker compose version --short
[551 ms] Docker Compose version: 2.3.3
[552 ms] Start: Run: docker ps -q -a --filter label=com.docker.compose.project=laminas_devcontainer --filter label=com.docker.compose.service=app
[569 ms] Start: Run: docker compose -f /home/edglobo/Desktop/container/projects/curso/3-modulo-comunicao-entre-sistemas/laminas/.devcontainer/docker-compose.yml --profile * config
[613 ms] name: devcontainer
services:
  app:
    build:
      context: /home/edglobo/Desktop/container/projects/curso/3-modulo-comunicao-entre-sistemas/laminas/.devcontainer
      dockerfile: Dockerfile
    command:
    - sleep
    - infinity
    network_mode: service:db
    volumes:
    - type: bind
      source: /home/edglobo/Desktop/container/projects/curso/3-modulo-comunicao-entre-sistemas
      target: /workspaces
      bind:
        create_host_path: true
  db:
    environment:
      MYSQL_DATABASE: mariadb
      MYSQL_PASSWORD: mariadb
      MYSQL_ROOT_PASSWORD: mariadb
      MYSQL_USER: mariadb
    image: mariadb:10.4
    networks:
      default: null
    restart: unless-stopped
    volumes:
    - type: volume
      source: mariadb-data
      target: /var/lib/mysql
      volume: {}
networks:
  default:
    name: devcontainer_default
volumes:
  mariadb-data:
    name: devcontainer_mariadb-data
[615 ms] Start: Run: docker -v
[631 ms] Start: Run: docker events --format {{json .}} --filter event=start
[634 ms] PersistedPath=/home/edglobo/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/data, ContainerHasLabels=false
[635 ms] Start: Run: docker compose -f /home/edglobo/Desktop/container/projects/curso/3-modulo-comunicao-entre-sistemas/laminas/.devcontainer/docker-compose.yml --profile * config
[679 ms] name: devcontainer
services:
  app:
    build:
      context: /home/edglobo/Desktop/container/projects/curso/3-modulo-comunicao-entre-sistemas/laminas/.devcontainer
      dockerfile: Dockerfile
    command:
    - sleep
    - infinity
    network_mode: service:db
    volumes:
    - type: bind
      source: /home/edglobo/Desktop/container/projects/curso/3-modulo-comunicao-entre-sistemas
      target: /workspaces
      bind:
        create_host_path: true
  db:
    environment:
      MYSQL_DATABASE: mariadb
      MYSQL_PASSWORD: mariadb
      MYSQL_ROOT_PASSWORD: mariadb
      MYSQL_USER: mariadb
    image: mariadb:10.4
    networks:
      default: null
    restart: unless-stopped
    volumes:
    - type: volume
      source: mariadb-data
      target: /var/lib/mysql
      volume: {}
networks:
  default:
    name: devcontainer_default
volumes:
  mariadb-data:
    name: devcontainer_mariadb-data
[682 ms] Start: Run: docker inspect --type image mcr.microsoft.com/devcontainers/php:0-8.2
[701 ms] local container features stored at: /home/edglobo/.vscode/extensions/ms-vscode-remote.remote-containers-0.280.0/dist/node_modules/vscode-dev-containers/container-features
[702 ms] Start: Run: tar --no-same-owner -x -f -
[717 ms] Docker Compose override file for building image:
version: '3.8'

services:
  app:
    build:
      dockerfile: /tmp/devcontainercli-edglobo/container-features/0.31.0-1677004130966/Dockerfile-with-features
      args:
        - BUILDKIT_INLINE_CACHE=1
        - _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label

[718 ms] Start: Run: docker compose --project-name laminas_devcontainer -f /home/edglobo/Desktop/container/projects/curso/3-modulo-comunicao-entre-sistemas/laminas/.devcontainer/docker-compose.yml -f /home/edglobo/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/data/docker-compose/docker-compose.devcontainer.build-1677004130982.yml build
Sending build context to Docker daemon  1.806kB
1 error occurred:
        * Error response from daemon: dockerfile parse error line 1: unknown instruction: .DOCKERIGNORE


[1062 ms] Error: Command failed: docker compose --project-name laminas_devcontainer -f /home/edglobo/Desktop/container/projects/curso/3-modulo-comunicao-entre-sistemas/laminas/.devcontainer/docker-compose.yml -f /home/edglobo/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/data/docker-compose/docker-compose.devcontainer.build-1677004130982.yml build
[1062 ms]     at yF (/home/edglobo/.vscode/extensions/ms-vscode-remote.remote-containers-0.280.0/dist/spec-node/devContainersSpecCLI.js:1896:412)
[1062 ms]     at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
[1062 ms]     at async sie (/home/edglobo/.vscode/extensions/ms-vscode-remote.remote-containers-0.280.0/dist/spec-node/devContainersSpecCLI.js:1896:2381)
[1062 ms]     at async iie (/home/edglobo/.vscode/extensions/ms-vscode-remote.remote-containers-0.280.0/dist/spec-node/devContainersSpecCLI.js:1878:2396)
[1062 ms]     at async xie (/home/edglobo/.vscode/extensions/ms-vscode-remote.remote-containers-0.280.0/dist/spec-node/devContainersSpecCLI.js:1945:2798)
[1062 ms]     at async Wf (/home/edglobo/.vscode/extensions/ms-vscode-remote.remote-containers-0.280.0/dist/spec-node/devContainersSpecCLI.js:1945:3750)
[1062 ms]     at async noe (/home/edglobo/.vscode/extensions/ms-vscode-remote.remote-containers-0.280.0/dist/spec-node/devContainersSpecCLI.js:2069:17325)
[1062 ms]     at async roe (/home/edglobo/.vscode/extensions/ms-vscode-remote.remote-containers-0.280.0/dist/spec-node/devContainersSpecCLI.js:2069:17066)
[1066 ms] Exit code 1
[1069 ms] Command failed: /usr/share/code/code --ms-enable-electron-run-as-node /home/edglobo/.vscode/extensions/ms-vscode-remote.remote-containers-0.280.0/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /home/edglobo/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --container-session-data-folder /tmp/devcontainers-4addaaa8-00d6-4643-8466-388d0a2cad531677004129745 --workspace-folder /home/edglobo/Desktop/container/projects/curso/3-modulo-comunicao-entre-sistemas/laminas --workspace-mount-consistency cached --id-label devcontainer.local_folder=/home/edglobo/Desktop/container/projects/curso/3-modulo-comunicao-entre-sistemas/laminas --id-label devcontainer.config_file=/home/edglobo/Desktop/container/projects/curso/3-modulo-comunicao-entre-sistemas/laminas/.devcontainer/devcontainer.json --log-level debug --log-format json --config /home/edglobo/Desktop/container/projects/curso/3-modulo-comunicao-entre-sistemas/laminas/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[1069 ms] Exit code 1
```

**My directories:**

![image](https://user-images.githubusercontent.com/49616761/220429504-1df5963e-99b2-40c4-bcb1-3fc5a3d2b8c2.png)

**devcontainer.json:**

```
// For format details, see https://aka.ms/devcontainer.json. For config options, see the
// README at: https://github.com/devcontainers/templates/tree/main/src/php-mariadb
{
	"name": "PHP & MariaDB",
	"dockerComposeFile": "docker-compose.yml",
	"service": "app",
	"workspaceFolder": "/workspaces/${localWorkspaceFolderBasename}",

	// Features to add to the dev container. More info: https://containers.dev/features.
	// "features": {},

	// For use with PHP or Apache (e.g.php -S localhost:8080 or apache2ctl start)
	"forwardPorts": [8080, 3306]

	// Use 'postCreateCommand' to run commands after the container is created.
	// "postCreateCommand": "sudo chmod a+x \"$(pwd)\" && sudo rm -rf /var/www/html && sudo ln -s \"$(pwd)\" /var/www/html"

	// Configure tool-specific properties.
	// "customizations": {},

	// Uncomment to connect as root instead. More info: https://aka.ms/dev-containers-non-root.
	// "remoteUser": "root"
}
```

**docker-compose.ym:**
```
version: '3.8'

services: 
  app:
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - ../..:/workspaces:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:db

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally. 
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  db:
    image: mariadb:10.4
    restart: unless-stopped
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mariadb
      MYSQL_DATABASE: mariadb
      MYSQL_USER: mariadb
      MYSQL_PASSWORD: mariadb

    # Add "forwardPorts": ["3306"] to **devcontainer.json** to forward MariaDB locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
  
volumes:
  mariadb-data:
```

**Dockerfile:**
```
FROM mcr.microsoft.com/devcontainers/php:0-8.2

# Install MariaDB client
RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
    && apt-get install -y mariadb-client \ 
    && apt-get clean -y && rm -rf /var/lib/apt/lists/*

# Install php-mysql driver
RUN docker-php-ext-install mysqli pdo pdo_mysql

# [Optional] Uncomment this section to install additional OS packages.
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends <your-package-list-here>

# [Optional] Uncomment this line to install global node packages.
# RUN su vscode -c "source /usr/local/share/nvm/nvm.sh && npm install -g <your-package-here>" 2>&1
```

**Comment by samruddhikhandale** [comment]
Thanks for the information. 

> [718 ms] Start: Run: docker compose --project-name laminas_devcontainer -f /home/edglobo/Desktop/container/projects/curso/3-modulo-comunicao-entre-sistemas/laminas/.devcontainer/docker-compose.yml -f /home/edglobo/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/data/docker-compose/docker-compose.devcontainer.build-1677004130982.yml build
Sending build context to Docker daemon  1.806kB

Looks like the dev container is failing to run the `docker compose .... build` command, can you try running `build` locally?

**Comment by chrmarti** [comment]
This appears to be a bug in Docker Compose 2.3.3: https://github.com/docker/compose/issues/9304

Please upgrade to a new version. Closing as fixed upstream.

**Comment by will3g** [comment]
Hi guys!

The problem solved, was the version of docker-compose. Thank you @chrmarti and @samruddhikhandale.

![image](https://user-images.githubusercontent.com/49616761/221362865-7cbab36c-768c-44c8-ad36-607683adcca4.png)
