### ISSUE TITLE
Setting `data-root` in docker daemon config file causes failing to mount

### ISSUE THREAD

**Issue by piquark6046** [devcontainers/cli#423]
### Summary
If you enable docker rootless and set value of `data-root` in docker daemon configuration file [^1], a failing to mount error is caused.
However, Deleting value of `data-root` resolves the error.

[^1]: `~/.config/docker/daemon.json`

### Environment
 - Operating System: Ubuntu 22.10
 - Docker: Docker Engine 23.0.1 (build a5ee5b1)

A LUKS-encrypted Ext4 partition [^2] is mounted as `/mnt/data`.
The value of the `data-root` is `/mnt/data/.dockerrootless`.

[^2]: A disk containing the partition is GPT-formatted SATA3 disk; Its system disk is GPT-formatted NVMe disk.

### Log
<details><summary>Log of Dev Container</summary>

```
[400 ms] Dev Containers 0.275.1 in VS Code 1.75.1 (441438abd1ac652551dbe4d408dfcec8a499b8bf).
[399 ms] Start: Resolving Remote
[410 ms] Setting up container for folder or workspace: /home/piqua/Documents/Workspaces/nodejs.code-workspace
[410 ms] Host: unix:///run/user/1000/docker.sock
[412 ms] Start: Check Docker is running
[412 ms] Start: Run: docker version --format {{.Server.APIVersion}}
[460 ms] Server API version: 1.42
[461 ms] Start: Run: docker volume ls -q
[504 ms] Start: Run: docker ps -q -a --filter label=vsch.local.folder=/home/piqua/Documents/Workspaces --filter label=vsch.quality=stable
[543 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/home/piqua/Documents/Workspaces --filter label=devcontainer.config_file=/home/piqua/Documents/Workspaces/.devcontainer/devcontainer.json
[585 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/home/piqua/Documents/Workspaces
[626 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/home/piqua/Documents/Workspaces
[666 ms] Start: Run: /usr/share/code/code --ms-enable-electron-run-as-node /home/piqua/.vscode/extensions/ms-vscode-remote.remote-containers-0.275.1/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /home/piqua/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --container-session-data-folder /tmp/devcontainers-352fd56f-2510-40f2-b89d-b40f5d6c1d261677421899059 --workspace-folder /home/piqua/Documents/Workspaces --workspace-mount-consistency cached --id-label devcontainer.local_folder=/home/piqua/Documents/Workspaces --id-label devcontainer.config_file=/home/piqua/Documents/Workspaces/.devcontainer/devcontainer.json --log-level debug --log-format json --config /home/piqua/Documents/Workspaces/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[822 ms] (node:64756) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
[822 ms] (Use `code --trace-deprecation ...` to show where the warning was created)
[822 ms] @devcontainers/cli 0.29.0. Node.js v16.14.2. linux 5.19.0-31-generic x64.
[822 ms] Start: Run: docker buildx version
[889 ms] github.com/docker/buildx v0.10.2 00ed17d
[889 ms] 
[889 ms] Start: Resolving Remote
[891 ms] Start: Run: git rev-parse --show-cdup
[895 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/home/piqua/Documents/Workspaces --filter label=devcontainer.config_file=/home/piqua/Documents/Workspaces/.devcontainer/devcontainer.json
[945 ms] Start: Run: docker inspect --type image mcr.microsoft.com/devcontainers/typescript-node:0-18
[987 ms] local container features stored at: /home/piqua/.vscode/extensions/ms-vscode-remote.remote-containers-0.275.1/dist/node_modules/vscode-dev-containers/container-features
[988 ms] Start: Run: tar --no-same-owner -x -f -
[1000 ms] Start: Run: docker build -f /tmp/devcontainercli-piqua/updateUID.Dockerfile-0.29.0 -t vsc-workspaces-3179bc9a0a8d271ce9233389479c8e86-uid --build-arg BASE_IMAGE=mcr.microsoft.com/devcontainers/typescript-node:0-18 --build-arg REMOTE_USER=node --build-arg NEW_UID=1000 --build-arg NEW_GID=1000 --build-arg IMAGE_USER=root /home/piqua/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/data/empty-folder
[+] Building 0.0s (2/2) FINISHED                                                
 => [internal] load .dockerignore                                          0.0s
 => => transferring context: 2B                                            0.0s
 => [internal] load build definition from updateUID.Dockerfile-0.29.0      0.0s
 => => transferring dockerfile: 1.33kB                                     0.0s
ERROR: failed to solve: failed to read dockerfile: failed to mount /mnt/data/.dockerrootless/tmp/buildkit-mount3282459247: [{Type:bind Source:/mnt/data/.dockerrootless/overlay2/7kbza1ujrjlrqhu0rwo99k4vd/diff Options:[rbind ro]}]: operation not permitted
[1391 ms] Error: Command failed: docker build -f /tmp/devcontainercli-piqua/updateUID.Dockerfile-0.29.0 -t vsc-workspaces-3179bc9a0a8d271ce9233389479c8e86-uid --build-arg BASE_IMAGE=mcr.microsoft.com/devcontainers/typescript-node:0-18 --build-arg REMOTE_USER=node --build-arg NEW_UID=1000 --build-arg NEW_GID=1000 --build-arg IMAGE_USER=root /home/piqua/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/data/empty-folder
[1391 ms]     at fie (/home/piqua/.vscode/extensions/ms-vscode-remote.remote-containers-0.275.1/dist/spec-node/devContainersSpecCLI.js:1915:1355)
[1392 ms]     at P7 (/home/piqua/.vscode/extensions/ms-vscode-remote.remote-containers-0.275.1/dist/spec-node/devContainersSpecCLI.js:1915:1291)
[1392 ms]     at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
[1392 ms]     at async Fie (/home/piqua/.vscode/extensions/ms-vscode-remote.remote-containers-0.275.1/dist/spec-node/devContainersSpecCLI.js:1921:2093)
[1392 ms]     at async Vf (/home/piqua/.vscode/extensions/ms-vscode-remote.remote-containers-0.275.1/dist/spec-node/devContainersSpecCLI.js:1921:3241)
[1392 ms]     at async eoe (/home/piqua/.vscode/extensions/ms-vscode-remote.remote-containers-0.275.1/dist/spec-node/devContainersSpecCLI.js:2045:17324)
[1393 ms]     at async Qse (/home/piqua/.vscode/extensions/ms-vscode-remote.remote-containers-0.275.1/dist/spec-node/devContainersSpecCLI.js:2045:17065)
[1398 ms] Exit code 1
[1401 ms] Command failed: /usr/share/code/code --ms-enable-electron-run-as-node /home/piqua/.vscode/extensions/ms-vscode-remote.remote-containers-0.275.1/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /home/piqua/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --container-session-data-folder /tmp/devcontainers-352fd56f-2510-40f2-b89d-b40f5d6c1d261677421899059 --workspace-folder /home/piqua/Documents/Workspaces --workspace-mount-consistency cached --id-label devcontainer.local_folder=/home/piqua/Documents/Workspaces --id-label devcontainer.config_file=/home/piqua/Documents/Workspaces/.devcontainer/devcontainer.json --log-level debug --log-format json --config /home/piqua/Documents/Workspaces/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[1402 ms] Exit code 1
```

</details>

**Comment by chrmarti** [comment]
Does this indicate a problem with the permissions you have set up on disk?
```
ERROR: failed to solve: failed to read dockerfile: failed to mount /mnt/data/.dockerrootless/tmp/buildkit-mount3282459247: [{Type:bind Source:/mnt/data/.dockerrootless/overlay2/7kbza1ujrjlrqhu0rwo99k4vd/diff Options:[rbind ro]}]: operation not permitted
```

Can you run the same command from the terminal?
```
docker build -f /tmp/devcontainercli-piqua/updateUID.Dockerfile-0.29.0 -t vsc-workspaces-3179bc9a0a8d271ce9233389479c8e86-uid --build-arg BASE_IMAGE=mcr.microsoft.com/devcontainers/typescript-node:0-18 --build-arg REMOTE_USER=node --build-arg NEW_UID=1000 --build-arg NEW_GID=1000 --build-arg IMAGE_USER=root /home/piqua/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/data/empty-folder
```

**Comment by piquark6046** [comment]
> Does this indicate a problem with the permissions you have set up on disk?

Other docker command like `docker pull ubuntu` works well.
The owner of `.dockerrootless` directory is `piqua`.

**Comment by piquark6046** [comment]
@chrmarti Do you need more data to reproduce?

**Comment by piquark6046** [comment]
I reconfigure this with the updated docker and it works.
I close this.

<details><summary>docker version</summary>
<p>

```
piqua@piqua-Desktop:~$ docker version
Client: Docker Engine - Community
 Version:           29.2.1
 API version:       1.53
 Go version:        go1.25.6
 Git commit:        a5c7197
 Built:             Mon Feb  2 17:17:19 2026
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          29.2.1
  API version:      1.53 (minimum version 1.44)
  Go version:       go1.25.6
  Git commit:       6bc6209
  Built:            Mon Feb  2 17:17:19 2026
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v2.2.1
  GitCommit:        dea7da592f5d1d2b7755e3a161be07f43fad8f75
 runc:
  Version:          1.3.4
  GitCommit:        v1.3.4-0-gd6d73eb8
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
 rootlesskit:
  Version:          2.3.6
  ApiVersion:       1.1.1
  NetworkDriver:    slirp4netns
  PortDriver:       builtin
  StateDir:         /run/user/1000/dockerd-rootless
 slirp4netns:
  Version:          1.2.1
  GitCommit:        09e31e92fa3d2a1d3ca261adaeb012c8d75a8194
```

</p>
</details>

**Comment by nvt261991-sys** [comment]
> I reconfigure this with the updated docker and it works.
> I close this.
> 
> <details><summary>docker version</summary>
> <p>
> 
> ```
> piqua@piqua-Desktop:~$ docker version
> Client: Docker Engine - Community
>  Version:           29.2.1
>  API version:       1.53
>  Go version:        go1.25.6
>  Git commit:        a5c7197
>  Built:             Mon Feb  2 17:17:19 2026
>  OS/Arch:           linux/amd64
>  Context:           default
> 
> Server: Docker Engine - Community
>  Engine:
>   Version:          29.2.1
>   API version:      1.53 (minimum version 1.44)
>   Go version:       go1.25.6
>   Git commit:       6bc6209
>   Built:            Mon Feb  2 17:17:19 2026
>   OS/Arch:          linux/amd64
>   Experimental:     false
>  containerd:
>   Version:          v2.2.1
>   GitCommit:        dea7da592f5d1d2b7755e3a161be07f43fad8f75
>  runc:
>   Version:          1.3.4
>   GitCommit:        v1.3.4-0-gd6d73eb8
>  docker-init:
>   Version:          0.19.0
>   GitCommit:        de40ad0
>  rootlesskit:
>   Version:          2.3.6
>   ApiVersion:       1.1.1
>   NetworkDriver:    slirp4netns
>   PortDriver:       builtin
>   StateDir:         /run/user/1000/dockerd-rootless
>  slirp4netns:
>   Version:          1.2.1
>   GitCommit:        09e31e92fa3d2a1d3ca261adaeb012c8d75a8194
> ```
> 
> </p>
> </details>

**Comment by nvt261991-sys** [comment]
> ### Summary
> If you enable docker rootless and set value of `data-root` in docker daemon configuration file [^1], a failing to mount error is caused.
> However, Deleting value of `data-root` resolves the error.
> 
> [^1]: `~/.config/docker/daemon.json`
> 
> ### Environment
>  - Operating System: Ubuntu 22.10
>  - Docker: Docker Engine 23.0.1 (build a5ee5b1)
> 
> A LUKS-encrypted Ext4 partition [^2] is mounted as `/mnt/data`.
> The value of the `data-root` is `/mnt/data/.dockerrootless`.
> 
> [^2]: A disk containing the partition is GPT-formatted SATA3 disk; Its system disk is GPT-formatted NVMe disk.
> 
> ### Log
> <details><summary>Log of Dev Container</summary>
> 
> ```
> [400 ms] Dev Containers 0.275.1 in VS Code 1.75.1 (441438abd1ac652551dbe4d408dfcec8a499b8bf).
> [399 ms] Start: Resolving Remote
> [410 ms] Setting up container for folder or workspace: /home/piqua/Documents/Workspaces/nodejs.code-workspace
> [410 ms] Host: unix:///run/user/1000/docker.sock
> [412 ms] Start: Check Docker is running
> [412 ms] Start: Run: docker version --format {{.Server.APIVersion}}
> [460 ms] Server API version: 1.42
> [461 ms] Start: Run: docker volume ls -q
> [504 ms] Start: Run: docker ps -q -a --filter label=vsch.local.folder=/home/piqua/Documents/Workspaces --filter label=vsch.quality=stable
> [543 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/home/piqua/Documents/Workspaces --filter label=devcontainer.config_file=/home/piqua/Documents/Workspaces/.devcontainer/devcontainer.json
> [585 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/home/piqua/Documents/Workspaces
> [626 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/home/piqua/Documents/Workspaces
> [666 ms] Start: Run: /usr/share/code/code --ms-enable-electron-run-as-node /home/piqua/.vscode/extensions/ms-vscode-remote.remote-containers-0.275.1/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /home/piqua/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --container-session-data-folder /tmp/devcontainers-352fd56f-2510-40f2-b89d-b40f5d6c1d261677421899059 --workspace-folder /home/piqua/Documents/Workspaces --workspace-mount-consistency cached --id-label devcontainer.local_folder=/home/piqua/Documents/Workspaces --id-label devcontainer.config_file=/home/piqua/Documents/Workspaces/.devcontainer/devcontainer.json --log-level debug --log-format json --config /home/piqua/Documents/Workspaces/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
> [822 ms] (node:64756) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
> [822 ms] (Use `code --trace-deprecation ...` to show where the warning was created)
> [822 ms] @devcontainers/cli 0.29.0. Node.js v16.14.2. linux 5.19.0-31-generic x64.
> [822 ms] Start: Run: docker buildx version
> [889 ms] github.com/docker/buildx v0.10.2 00ed17d
> [889 ms] 
> [889 ms] Start: Resolving Remote
> [891 ms] Start: Run: git rev-parse --show-cdup
> [895 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/home/piqua/Documents/Workspaces --filter label=devcontainer.config_file=/home/piqua/Documents/Workspaces/.devcontainer/devcontainer.json
> [945 ms] Start: Run: docker inspect --type image mcr.microsoft.com/devcontainers/typescript-node:0-18
> [987 ms] local container features stored at: /home/piqua/.vscode/extensions/ms-vscode-remote.remote-containers-0.275.1/dist/node_modules/vscode-dev-containers/container-features
> [988 ms] Start: Run: tar --no-same-owner -x -f -
> [1000 ms] Start: Run: docker build -f /tmp/devcontainercli-piqua/updateUID.Dockerfile-0.29.0 -t vsc-workspaces-3179bc9a0a8d271ce9233389479c8e86-uid --build-arg BASE_IMAGE=mcr.microsoft.com/devcontainers/typescript-node:0-18 --build-arg REMOTE_USER=node --build-arg NEW_UID=1000 --build-arg NEW_GID=1000 --build-arg IMAGE_USER=root /home/piqua/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/data/empty-folder
> [+] Building 0.0s (2/2) FINISHED                                                
>  => [internal] load .dockerignore                                          0.0s
>  => => transferring context: 2B                                            0.0s
>  => [internal] load build definition from updateUID.Dockerfile-0.29.0      0.0s
>  => => transferring dockerfile: 1.33kB                                     0.0s
> ERROR: failed to solve: failed to read dockerfile: failed to mount /mnt/data/.dockerrootless/tmp/buildkit-mount3282459247: [{Type:bind Source:/mnt/data/.dockerrootless/overlay2/7kbza1ujrjlrqhu0rwo99k4vd/diff Options:[rbind ro]}]: operation not permitted
> [1391 ms] Error: Command failed: docker build -f /tmp/devcontainercli-piqua/updateUID.Dockerfile-0.29.0 -t vsc-workspaces-3179bc9a0a8d271ce9233389479c8e86-uid --build-arg BASE_IMAGE=mcr.microsoft.com/devcontainers/typescript-node:0-18 --build-arg REMOTE_USER=node --build-arg NEW_UID=1000 --build-arg NEW_GID=1000 --build-arg IMAGE_USER=root /home/piqua/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/data/empty-folder
> [1391 ms]     at fie (/home/piqua/.vscode/extensions/ms-vscode-remote.remote-containers-0.275.1/dist/spec-node/devContainersSpecCLI.js:1915:1355)
> [1392 ms]     at P7 (/home/piqua/.vscode/extensions/ms-vscode-remote.remote-containers-0.275.1/dist/spec-node/devContainersSpecCLI.js:1915:1291)
> [1392 ms]     at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
> [1392 ms]     at async Fie (/home/piqua/.vscode/extensions/ms-vscode-remote.remote-containers-0.275.1/dist/spec-node/devContainersSpecCLI.js:1921:2093)
> [1392 ms]     at async Vf (/home/piqua/.vscode/extensions/ms-vscode-remote.remote-containers-0.275.1/dist/spec-node/devContainersSpecCLI.js:1921:3241)
> [1392 ms]     at async eoe (/home/piqua/.vscode/extensions/ms-vscode-remote.remote-containers-0.275.1/dist/spec-node/devContainersSpecCLI.js:2045:17324)
> [1393 ms]     at async Qse (/home/piqua/.vscode/extensions/ms-vscode-remote.remote-containers-0.275.1/dist/spec-node/devContainersSpecCLI.js:2045:17065)
> [1398 ms] Exit code 1
> [1401 ms] Command failed: /usr/share/code/code --ms-enable-electron-run-as-node /home/piqua/.vscode/extensions/ms-vscode-remote.remote-containers-0.275.1/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /home/piqua/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --container-session-data-folder /tmp/devcontainers-352fd56f-2510-40f2-b89d-b40f5d6c1d261677421899059 --workspace-folder /home/piqua/Documents/Workspaces --workspace-mount-consistency cached --id-label devcontainer.local_folder=/home/piqua/Documents/Workspaces --id-label devcontainer.config_file=/home/piqua/Documents/Workspaces/.devcontainer/devcontainer.json --log-level debug --log-format json --config /home/piqua/Documents/Workspaces/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
> [1402 ms] Exit code 1
> ```
> 
> </details>
