### ISSUE TITLE
Cannot find credentials managed by credential helpers when attempting to download features.

### ISSUE THREAD

**Issue by Clockwork-Muse** [devcontainers/cli#435]
To prevent the storage of plain-text credentials, docker publishes [credential helpers](https://github.com/docker/docker-credential-helpers).  While docker itself transparently works with these credential helpers (to the point that it will auto-configure itself if it finds them in `$PATH`), the current cli is not set up to handle them, and fails to find the resulting credentials.

With a credential helper installed, `~/.docker/config.json` looks like this:
```json
{
	"auths": {
		"private.azurecr.io": {}
	},
	"credsStore": "secretservice"
}
```

When attempting to build a container that would use these credentials, it fails to find them:
```log
devcontainer build /tmp/somedir/ --log-level trace
(node:278306) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `code --trace-deprecation ...` to show where the warning was created)
[11 ms] @devcontainers/cli 0.31.0. Node.js v16.14.2. linux 5.19.0-32-generic x64.
[11 ms] Start: Run: docker buildx version
[72 ms] Stop (61 ms): Run: docker buildx version
[72 ms] github.com/docker/buildx v0.10.2 00ed17d
[73 ms] 
[75 ms] Start: Run: docker inspect --type image private.azurecr.io/alpine
[114 ms] Stop (39 ms): Run: docker inspect --type image private.azurecr.io/alpine
[114 ms] > input: docker.io/private.azurecr.io/alpine
[114 ms] >
[114 ms] > resource: docker.io/private.azurecr.io/alpine
[114 ms] > id: alpine
[114 ms] > version: latest
[114 ms] > owner: private.azurecr.io
[114 ms] > namespace: private.azurecr.io
[114 ms] > registry: docker.io
[114 ms] > path: private.azurecr.io/alpine
[114 ms] manifest url: https://registry-1.docker.io/v2/private.azurecr.io/alpine/manifests/latest
[383 ms] [httpOci] Attempting to authenticate via 'Bearer' auth.
[385 ms] [httpOci] No authentication credentials found for registry 'docker.io'. Accessing anonymously.
[385 ms] [httpOci] Attempting to fetch bearer token from:  https://auth.docker.io/token?service=registry.docker.io&scope=repository:private.azurecr.io/alpine:pull
[918 ms] [httpOci] 401 on reattempt after auth: https://registry-1.docker.io/v2/private.azurecr.io/alpine/manifests/latest
[918 ms] Did not fetch target with expected mimetype 'application/vnd.docker.distribution.manifest.v2+json': {"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":[{"Type":"repository","Class":"","Name":"private.azurecr.io/alpine","Action":"pull"}]}]}
[1177 ms] [httpOci] Attempting to authenticate via 'Bearer' auth.
[1178 ms] [httpOci] No authentication credentials found for registry 'docker.io'. Accessing anonymously.
[1178 ms] [httpOci] Attempting to fetch bearer token from:  https://auth.docker.io/token?service=registry.docker.io&scope=repository:private.azurecr.io/alpine:pull
[1719 ms] [httpOci] 401 on reattempt after auth: https://registry-1.docker.io/v2/private.azurecr.io/alpine/manifests/latest
[1719 ms] Did not fetch target with expected mimetype 'application/vnd.oci.image.index.v1+json': {"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":[{"Type":"repository","Class":"","Name":"private.azurecr.io/alpine","Action":"pull"}]}]}
[1719 ms] Error fetching image details: No manifest found for docker.io/private.azurecr.io/alpine.
[1719 ms] Start: Run: docker pull private.azurecr.io/alpine
Using default tag: latest
latest: Pulling from alpine
eaead16dc43b: Already exists 
e7be320108a5: Already exists 
a1de773113e3: Already exists 
Digest: sha256:1101019e4a775ca0126a627f9f1f649ddbf94c2097887bf08caae0a9ece56255
Status: Downloaded newer image for private.azurecr.io/alpine:latest
private.azurecr.io/alpine:latest
[4075 ms] Stop (2356 ms): Run: docker pull private.azurecr.io/alpine
[4076 ms] Start: Run: docker inspect --type image private.azurecr.io/alpine
[4117 ms] Stop (41 ms): Run: docker inspect --type image private.azurecr.io/alpine
[4117 ms] Start: Run: docker inspect --type image private.azurecr.io/alpine
[4156 ms] Stop (39 ms): Run: docker inspect --type image private.azurecr.io/alpine
[4157 ms] local container features stored at: /home/simhoff/.vscode/extensions/ms-vscode-remote.remote-containers-0.282.0/dist/node_modules/vscode-dev-containers/container-features
[4158 ms] Start: Run: tar --no-same-owner -x -f -
[4171 ms] Stop (13 ms): Run: tar --no-same-owner -x -f -
[4171 ms] workspace root: /tmp/somedir
[4176 ms] Loaded /home/simhoff/.vscode/extensions/ms-vscode-remote.remote-containers-0.282.0/dist/node_modules/vscode-dev-containers/container-features/devcontainer-features.json, which declares 25 features and does not contain explicit source info.
[4176 ms] --- Processing User Features ----
[4176 ms] configPath: /tmp/somedir/.devcontainer/devcontainer.json
[4176 ms] * Processing feature: private.azurecr.io/devcontainers/features/hello:1
[4177 ms] > input: private.azurecr.io/devcontainers/features/hello:1
[4177 ms] >
[4177 ms] > resource: private.azurecr.io/devcontainers/features/hello
[4177 ms] > id: hello
[4177 ms] > version: 1
[4177 ms] > owner: devcontainers
[4177 ms] > namespace: devcontainers/features
[4177 ms] > registry: private.azurecr.io
[4177 ms] > path: devcontainers/features/hello
[4177 ms] manifest url: https://private.azurecr.io/v2/devcontainers/features/hello/manifests/1
[4491 ms] [httpOci] Attempting to authenticate via 'Bearer' auth.
[4492 ms] [httpOci] No authentication credentials found for registry 'private.azurecr.io'. Accessing anonymously.
[4492 ms] [httpOci] Attempting to fetch bearer token from:  https://private.azurecr.io/oauth2/token?service=private.azurecr.io&scope=repository:devcontainers/features/hello:pull
[4807 ms] [-] HTTP request failed with status code 401: : Unauthorized
[4807 ms] [httpOci] Could not fetch bearer token for 'private.azurecr.io': Error: HTTP 401: Unauthorized
[4807 ms] [httpOci] ERR: Failed to fetch Bearer token from registry.
[4807 ms] Request failed
[4807 ms] (!) WARNING: Falling back to deprecated GitHub Release syntax. See https://github.com/devcontainers/spec/blob/main/proposals/devcontainer-features.md#referencing-a-feature for updated specification.
[4807 ms] Github feature.
[4807 ms] Could not resolve Feature 'private.azurecr.io/devcontainers/features/hello:1'.  Ensure the Feature is published and accessible from your current environment.
Error: Failed to process feature private.azurecr.io/devcontainers/features/hello:1
    at bne (/home/simhoff/.vscode/extensions/ms-vscode-remote.remote-containers-0.282.0/dist/spec-node/devContainersSpecCLI.js:1850:3109)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async am (/home/simhoff/.vscode/extensions/ms-vscode-remote.remote-containers-0.282.0/dist/spec-node/devContainersSpecCLI.js:1850:2243)
    at async Uf (/home/simhoff/.vscode/extensions/ms-vscode-remote.remote-containers-0.282.0/dist/spec-node/devContainersSpecCLI.js:1853:1672)
    at async fm (/home/simhoff/.vscode/extensions/ms-vscode-remote.remote-containers-0.282.0/dist/spec-node/devContainersSpecCLI.js:1853:207)
    at async foe (/home/simhoff/.vscode/extensions/ms-vscode-remote.remote-containers-0.282.0/dist/spec-node/devContainersSpecCLI.js:2069:28181)
    at async loe (/home/simhoff/.vscode/extensions/ms-vscode-remote.remote-containers-0.282.0/dist/spec-node/devContainersSpecCLI.js:2069:25018)
{"outcome":"error","message":"Failed to process feature private.azurecr.io/devcontainers/features/hello:1","description":"An error occurred building the container."}
```

<hr />

Note that this is a separate issue from #434 .  In that issue, I was deliberately removing the credential helper in an attempt to troubleshoot this one.  There, it finds the credentials, but is still unable to log in, whereas here the credentials are not found.

**Comment by Clockwork-Muse** [comment]
Silly me.

Duplicate of #349
