### ISSUE TITLE
VSCode launch up broken

### ISSUE THREAD

**Issue by naturedamends** [devcontainers/cli#505]
```
 /usr/bin/env 'NODE_OPTIONS=--require /vscode/vscode-server/bin/linux-x64/704e
d70d4fd1c6bd6342c436f1ede30d1cff4710/extensions/ms-vscode.js-debug/src/bootloader.js --inspect-publish-uid=htt
p' 'VSCODE_INSPECTOR_OPTIONS={"inspectorIpc":"/tmp/node-cdp.526-dd19cec5-4.sock","deferredMode":false,"waitFor
Debugger":"","execPath":"/usr/local/bin/node","onlyEntrypoint":false,"autoAttachMode":"always","mandatePortTra
cking":true,"fileCallback":"/tmp/node-debug-callback-dce2b4aa8014bd78"}' /usr/local/bin/node ./built/spec-node
/devContainersSpecCLI.js up --workspace-folder /workspaces/cli/src/test/configs/example --log-level debug 
Debugger attached.
Waiting for the debugger to disconnect...
/workspaces/cli/built/spec-node/featuresCLI/testCommandImpl.js:31
const chalk_1 = __importDefault(require("chalk"));
                                ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /workspaces/cli/node_modules/chalk/source/index.js from /workspaces/cli/built/spec-node/featuresCLI/testCommandImpl.js not supported.
Instead change the require of index.js in /workspaces/cli/built/spec-node/featuresCLI/testCommandImpl.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/workspaces/cli/built/spec-node/featuresCLI/testCommandImpl.js:31:33)
    at Object.<anonymous> (/workspaces/cli/built/spec-node/featuresCLI/test.js:8:27)
    at Object.<anonymous> (/workspaces/cli/built/spec-node/devContainersSpecCLI.js:53:16) {
  code: 'ERR_REQUIRE_ESM'
}
```

**Comment by naturedamends** [comment]
sorry i silly. Installing via `yarn install --frozen-lockfile` fixed this

Should
```
"postCreateCommand": "yarn install",
```
be changed in the devcontainer file?

**Comment by samruddhikhandale** [comment]
Hi 👋 

You might have already tried this, however, can you create a PR from https://github.com/devcontainers/cli/compare UI ? Else, I can help open a PR if needed.

**Comment by naturedamends** [comment]
> Hi 👋
> 
> You might have already tried this, however, can you create a PR from https://github.com/devcontainers/cli/compare UI ? Else, I can help open a PR if needed.

Arr, I didn't see the option to add the change to the compare via forks options. and i wasn't presented a notification.

I've created a PR for you https://github.com/devcontainers/cli/pull/509. Feel free to close it. I'm not sure if its intentional thing to tell devs to fix the issue... however, as a newbie I like things to work out of the box IMO
