### ISSUE TITLE
Error: Missing node-pty

### ISSUE THREAD

**Issue by alfonsomhc** [devcontainers/cli#536]
I get this error when I try to run the example project:
```
> uname -a
Linux HTY23123 5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

> node --version
v18.16.0

> npm list --global
/home/myuser/.nvm/versions/node/v18.16.0/lib
├── @devcontainers/cli@0.41.0
├── corepack@0.17.0
├── node-pty@0.10.1
└── npm@9.5.1

> devcontainer up --workspace-folder vscode-remote-try-rust
innerError Error: Cannot find module '../build/Debug/pty.node'
Require stack:
- /usr/local/lib/node_modules/@devcontainers/cli/node_modules/node-pty/lib/unixTerminal.js
- /usr/local/lib/node_modules/@devcontainers/cli/node_modules/node-pty/lib/index.js
- /usr/local/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js
- /usr/local/lib/node_modules/@devcontainers/cli/devcontainer.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
    at Module._load (node:internal/modules/cjs/loader:920:27)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/@devcontainers/cli/node_modules/node-pty/lib/unixTerminal.js:30:15)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/local/lib/node_modules/@devcontainers/cli/node_modules/node-pty/lib/unixTerminal.js',
    '/usr/local/lib/node_modules/@devcontainers/cli/node_modules/node-pty/lib/index.js',
    '/usr/local/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js',
    '/usr/local/lib/node_modules/@devcontainers/cli/devcontainer.js'
  ]
}
Error: Missing node-pty
    at Jx (/usr/local/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:1670:1908)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async gn (/usr/local/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:1669:13220)
    at async mo (/usr/local/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:1961:4595)
    at async vh (/usr/local/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:1961:3673)
    at async Eae (/usr/local/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:2092:10371)
    at async gae (/usr/local/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:2092:10112)
{"outcome":"error","message":"Missing node-pty","description":"An error occurred setting up the container."}
```
Please help :)

**Comment by chrmarti** [comment]
The installation at `/usr/local/lib/node_modules/@devcontainers/cli/node_modules/node-pty` appears to be incomplete. Could you try reinstalling `@devcontainers/cli` and check for errors during installation?

**Comment by alfonsomhc** [comment]
Thank you, reinstalling did the trick. The original installation had probably failed because I had not configured the certificate (I'm behind a proxy) correctly in npm. I've done that now, and after a reinstall it seems to work.
