### ISSUE TITLE
Unable to build a devcontainer features with podman

### ISSUE THREAD

**Issue by dubielt1** [devcontainers/cli#548]
`.devcontainer/Dockerfile`:
```Dockerfile
FROM mcr.microsoft.com/devcontainers/base:ubuntu-22.04

RUN apt-get update && apt-get install -y \
    foot-terminfo \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /opt/
 RUN wget https://github.com/neovim/neovim/releases/download/stable/nvim-linux64.tar.gz \
    && tar xzvf ./nvim-linux64.tar.gz \
    && rm ./nvim-linux64.tar.gz

ENV PATH="$PATH:/opt/nvim-linux64/bin"
```

`.devcontainer/devcontainer.json`:
```JSONC
{
  "name": "ide-py",
  "build": {
    "dockerfile": "Dockerfile"
  },
  "features": {
    "ghcr.io/devcontainers/features/python:1": {
      "version": "latest"
    }
  }
  //"runArgs": ["--security-opt", "label=disable"],
}
```

build command: `devcontainer build --docker-path podman --workspace-folder ./`

<details>
  <summary>devcontainer Error Encountered</summary>
  
  ```
[3/3] STEP 10/13: RUN --mount=type=bind,from=dev_containers_feature_content_source,source=python_1,target=/tmp/build-features-src/python_1     cp -ar /tmp/build-features-src/python_1 /tmp/dev-container-features  && chmod -R 0755 /tmp/dev-container-features/python_1  && cd /tmp/dev-container-features/python_1  && chmod +x ./devcontainer-features-install.sh  && ./devcontainer-features-install.sh  && rm -rf /tmp/dev-container-features/python_1
cp: cannot access '/tmp/build-features-src/python_1': Permission denied
Error: building at STEP "RUN --mount=type=bind,from=dev_containers_feature_content_source,source=python_1,target=/tmp/build-features-src/python_1 cp -ar /tmp/build-features-src/python_1 /tmp/dev-container-features  && chmod -R 0755 /tmp/dev-container-features/python_1  && cd /tmp/dev-container-features/python_1  && chmod +x ./devcontainer-features-install.sh  && ./devcontainer-features-install.sh  && rm -rf /tmp/dev-container-features/python_1": while running runtime: exit status 1
Error: Command failed: podman buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /tmp/devcontainercli-tdubiel/container-features/0.43.0-1686449407786/Dockerfile-with-features -t vsc-py-28d0486e1c2b00c4e973d123ef6f69141ddf0a260b975d4df1c9e87959307d37 --target dev_containers_target_stage --build-context dev_containers_feature_content_source=/tmp/devcontainercli-tdubiel/container-features/0.43.0-1686449407786 --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label --build-arg _DEV_CONTAINERS_IMAGE_USER=root --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp /var/home/tdubiel/Code/ide-toolbox-setup/py/.devcontainer
    at xte (/var/home/tdubiel/.nvm/versions/node/v18.16.0/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:2005:1698)
    at async zw (/var/home/tdubiel/.nvm/versions/node/v18.16.0/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:2004:1691)
    at async cne (/var/home/tdubiel/.nvm/versions/node/v18.16.0/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:2152:20389)
    at async lne (/var/home/tdubiel/.nvm/versions/node/v18.16.0/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:2152:18322)
{"outcome":"error","message":"Command failed: podman buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /tmp/devcontainercli-tdubiel/container-features/0.43.0-1686449407786/Dockerfile-with-features -t vsc-py-28d0486e1c2b00c4e973d123ef6f69141ddf0a260b975d4df1c9e87959307d37 --target dev_containers_target_stage --build-context dev_containers_feature_content_source=/tmp/devcontainercli-tdubiel/container-features/0.43.0-1686449407786 --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label --build-arg _DEV_CONTAINERS_IMAGE_USER=root --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp /var/home/tdubiel/Code/ide-toolbox-setup/py/.devcontainer","description":"An error occurred building the image."}
  ```
</details>

<details>
<summary>podman info --debug output</summary>

```
host:
  arch: amd64
  buildahVersion: 1.29.0
  cgroupControllers:
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.7-2.fc38.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.7, commit: '
  cpuUtilization:
    idlePercent: 97.24
    systemPercent: 1.76
    userPercent: 0.99
  cpus: 16
  distribution:
    distribution: fedora
    variant: sericea
    version: "38"
  eventLogger: journald
  hostname: fedora
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 524288
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 524288
      size: 65536
  kernel: 6.2.9-300.fc38.x86_64
  linkmode: dynamic
  logDriver: journald
  memFree: 22976339968
  memTotal: 33416204288
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: crun-1.8.3-2.fc38.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.8.3
      commit: 59f2beb7efb0d35611d5818fd0311883676f6f7e
      rundir: /run/user/1000/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +LIBKRUN +WASM:wasmedge +YAJL
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.0-12.fc38.x86_64
    version: |-
      slirp4netns version 1.2.0
      commit: 656041d45cfca7a4176f6b7eed9e4fe6c11e8383
      libslirp: 4.7.0
      SLIRP_CONFIG_VERSION_MAX: 4
      libseccomp: 2.5.3
  swapFree: 8589930496
  swapTotal: 8589930496
  uptime: 2h 30m 42.00s (Approximately 0.08 days)
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
  - quay.io
store:
  configFile: /var/home/tdubiel/.config/containers/storage.conf
  containerStore:
    number: 4
    paused: 0
    running: 3
    stopped: 1
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/tdubiel/.local/share/containers/storage
  graphRootAllocated: 137338290176
  graphRootUsed: 8593375232
  graphStatus:
    Backing Filesystem: btrfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 48
  runRoot: /run/user/1000/containers
  transientStore: false
  volumePath: /home/tdubiel/.local/share/containers/storage/volumes
version:
  APIVersion: 4.4.2
  Built: 1677669759
  BuiltTime: Wed Mar  1 05:22:39 2023
  GitCommit: ""
  GoVersion: go1.20.1
  Os: linux
  OsArch: linux/amd64
  Version: 4.4.2
```
</details>

env:
- `node --version`: `v18.16.0`
- `devcontainer --version`: `0.43.0`

---

Possibly related topics?
- SELinux shared labels: https://github.com/containers/podman/issues/15423

**Comment by fsdrw08** [comment]
some to me, I think podman does not support `podman buildx` command

**Comment by chrmarti** [comment]
Related: https://github.com/microsoft/vscode-remote-release/issues/1333

**Comment by dubielt1** [comment]
@chrmarti - thank you sharing the related ticket

I must admit, I am not sure which rabbit hole to start with, or if the implication is that this won't work at all... an additional hint if this is possible would be appreciated

---

I created a `$HOME/.config/containers/storage.conf`, with these contents: ([docs](https://github.com/containers/storage/blob/main/docs/containers-storage.conf.5.md) for future readers)
```conf
[storage]
driver = "overlay"

[storage.options.overlay]
mount_program = "/usr/bin/fuse-overlayfs"
```

followed by `podman system reset` and a re-attempted `devcontainer build...`, but it failed in the same manner as before.

---

I then followed the above procedure, but for `$HOME/.config/containers/containers.conf`: ([docs](https://github.com/containers/common/blob/main/docs/containers.conf.5.md) for future readers)
```conf
[containers]
volumes=["/tmp:/tmp:Z"]
```

This also failed, much earlier in the build process. This attempt was probably misguided.

---

If permissive/disabled SELinux is a viable solution, I would be open to that. This is my system for personal dev only

**Comment by chrmarti** [comment]
I'm not familiar with SELinux. Commenters in https://github.com/microsoft/vscode-remote-release/issues/1333 have suggested that the `z`/`Z` flags (https://docs.docker.com/storage/bind-mounts/#configure-the-selinux-label) might help, but I haven't tried. Note that the documentation warns about using `Z` on system folders.

**Comment by dubielt1** [comment]
@chrmarti, after looking into what the `z`/`Z` flags do, I found a way to do the same thing with SELinux commands. The below successfully builds the devcontainer, without permanently changing the system or SELinux config.

`chcon` tweaks SELinux so that the build succeeds, and `restorecon` reverts said-tweak

```bash
sudo chcon -R -t container_file_t /tmp/
devcontainer build --docker-path podman --workspace-folder ./
sudo restorecon -RFv /tmp/
```

**Disclaimer**: I lack the expertise to determine if there are downsides to doing this. It _seems_ harmless

Notes for the curious:

- The `z` flag does a similar thing to the above command, relabeling the directory as `container_file_t` ([src](https://unix.stackexchange.com/questions/651198/podman-volume-mounts-when-to-use-the-z-or-z-suffix))
- `restorecon` required the `F` (force) flag. Without it, it would log the following when using the verbose flag: `/tmp not reset as customized by admin to system_u:object_r:container_file_t:s0`

**Comment by gilesknap** [comment]
@dubielt1 please consider re-opening this bug.

Making changes to the security settings on /tmp is not available to non-root users. At our facility we don't give root access to developers, only the sysadmins have this right.

podman fits into this approach perfectly because it allows us to build and use containers without root permission.

I've already asked our sysadmins to change the SELinux settings on /tmp on our workstation build. Their response was - that is the default settings that RedHat provide so we don't want to change them.

I assume at present devcontainers do not change the command line arguments they use based upon podman/docker. But really in order to support podman on its native distro of RedHat this needs to be the case. Or at least expose the arguments as a setting that we can override.

In the devcontainer JSON we get to specify the arguments for building containers. But the cause of this issue (which happens when adding 'features' to your devcontainer) is not exposed in the same way.

**Comment by gilesknap** [comment]
@chrmarti thanks! Sorry, I missed the mention of the commit.

**Comment by worldofgeese** [comment]
> @gilesknap I have added a fix that will use the `z` flag for this mount when using buildah. Hope that makes sense. This change will be in the next version of the CLI.

@chrmarti, @n1hility of Red Hat was taking a look at this issue too. Does this fix solve for all rootless use-cases of Podman powering devcontainers?

**Comment by chrmarti** [comment]
@worldofgeese This only takes care of the build context for adding feature scripts.

**Comment by nikolaseu** [comment]
Is this still not working? This is a basic test with:

```
// For format details, see https://aka.ms/devcontainer.json. For config options, see the
// README at: https://github.com/devcontainers/templates/tree/main/src/debian
{
	"name": "Debian",
	// Or use a Dockerfile or Docker Compose file. More info: https://containers.dev/guide/dockerfile
	"image": "mcr.microsoft.com/devcontainers/base:bullseye",

	// Features to add to the dev container. More info: https://containers.dev/features.
	"features": {
        // https://github.com/devcontainers/features/tree/main/src/common-utils
        "ghcr.io/devcontainers/features/common-utils:2": {
            "installZsh": true,
            "configureZshAsDefaultShell": true,
            "installOhMyZsh": true,
            "upgradePackages": false
        }
    },

	// Use 'forwardPorts' to make a list of ports inside the container available locally.
	// "forwardPorts": [],

	// Configure tool-specific properties.
	// "customizations": {},

	// Uncomment to connect as root instead. More info: https://aka.ms/dev-containers-non-root.
	// "remoteUser": "root"
}
```

The error:

```
[2025-11-05T11:36:29.348Z] Dev Containers 0.427.0 in VS Code 1.105.1 (7d842fb85a0275a4a8e4d7e040d2625abbf7f084).
[2025-11-05T11:36:29.348Z] Start: Resolving Remote
[2025-11-05T11:36:29.354Z] Setting up container for folder or workspace: /Users/user/Projects/test
[2025-11-05T11:36:29.354Z] Start: Check Docker is running
[2025-11-05T11:36:29.355Z] Start: Run: podman version
[2025-11-05T11:36:29.467Z] Client:        Podman Engine
Version:       5.6.2
API Version:   5.6.2
Go Version:    go1.25.1
Built:         Tue Sep 30 16:50:46 2025
Build Origin:  brew
OS/Arch:       darwin/arm64

Server:       Podman Engine
[2025-11-05T11:36:29.467Z] Version:      5.6.2
API Version:  5.6.2
Go Version:   go1.24.7
Git Commit:   9dd5e1ed33830612bc200d7a13db00af6ab865a4
Built:        Tue Sep 30 02:00:00 2025
OS/Arch:      linux/arm64
[2025-11-05T11:36:29.468Z] Stop (113 ms): Run: podman version
[2025-11-05T11:36:29.468Z] Stop (114 ms): Check Docker is running
[2025-11-05T11:36:29.469Z] Start: Run: podman volume ls -q
[2025-11-05T11:36:29.532Z] Stop (63 ms): Run: podman volume ls -q
[2025-11-05T11:36:29.533Z] Start: Run: podman ps -q -a --filter label=vsch.local.folder=/Users/user/Projects/test --filter label=vsch.quality=stable
[2025-11-05T11:36:29.592Z] Stop (59 ms): Run: podman ps -q -a --filter label=vsch.local.folder=/Users/user/Projects/test --filter label=vsch.quality=stable
[2025-11-05T11:36:29.592Z] Start: Run: podman ps -q -a --filter label=devcontainer.local_folder=/Users/user/Projects/test --filter label=devcontainer.config_file=/Users/user/Projects/test/.devcontainer/devcontainer.json
[2025-11-05T11:36:29.649Z] Stop (57 ms): Run: podman ps -q -a --filter label=devcontainer.local_folder=/Users/user/Projects/test --filter label=devcontainer.config_file=/Users/user/Projects/test/.devcontainer/devcontainer.json
[2025-11-05T11:36:29.650Z] Start: Run: podman ps -q -a --filter label=devcontainer.local_folder=/Users/user/Projects/test
[2025-11-05T11:36:29.715Z] Stop (65 ms): Run: podman ps -q -a --filter label=devcontainer.local_folder=/Users/user/Projects/test
[2025-11-05T11:36:29.715Z] Start: Run: podman ps -q -a --filter label=devcontainer.local_folder=/Users/user/Projects/test
[2025-11-05T11:36:29.781Z] Stop (66 ms): Run: podman ps -q -a --filter label=devcontainer.local_folder=/Users/user/Projects/test
[2025-11-05T11:36:29.781Z] Running Dev Containers CLI:   up --user-data-folder /Users/user/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --docker-path podman --container-session-data-folder /tmp/devcontainers-2459b8e5-1ad1-4dc2-aa8c-239e774836491762342588983 --workspace-folder /Users/user/Projects/test --workspace-mount-consistency cached --gpu-availability detect --id-label devcontainer.local_folder=/Users/user/Projects/test --id-label devcontainer.config_file=/Users/user/Projects/test/.devcontainer/devcontainer.json --log-level debug --log-format json --config /Users/user/Projects/test/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root --include-configuration --include-merged-configuration
[2025-11-05T11:36:29.793Z] ProxyResolver#loadSystemCertificates count
[2025-11-05T11:36:29.794Z] ProxyResolver#loadSystemCertificates count filtered
[2025-11-05T11:36:29.794Z] Start: Run: /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin) /Users/user/.vscode/extensions/ms-vscode-remote.remote-containers-0.427.0/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /Users/user/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --docker-path podman --container-session-data-folder /tmp/devcontainers-2459b8e5-1ad1-4dc2-aa8c-239e774836491762342588983 --workspace-folder /Users/user/Projects/test --workspace-mount-consistency cached --gpu-availability detect --id-label devcontainer.local_folder=/Users/user/Projects/test --id-label devcontainer.config_file=/Users/user/Projects/test/.devcontainer/devcontainer.json --log-level debug --log-format json --config /Users/user/Projects/test/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root --include-configuration --include-merged-configuration
[2025-11-05T11:36:29.891Z] @devcontainers/cli 0.80.1. Node.js v22.19.0. darwin 25.1.0 arm64.
[2025-11-05T11:36:29.891Z] Start: Run: podman buildx version
[2025-11-05T11:36:29.965Z] Stop (74 ms): Run: podman buildx version
[2025-11-05T11:36:29.965Z] buildah 1.41.5
[2025-11-05T11:36:29.965Z] 
[2025-11-05T11:36:29.966Z] Start: Run: podman -v
[2025-11-05T11:36:29.977Z] Stop (11 ms): Run: podman -v
[2025-11-05T11:36:29.977Z] Start: Resolving Remote
[2025-11-05T11:36:29.978Z] Start: Run: git rev-parse --show-cdup
[2025-11-05T11:36:29.987Z] Stop (9 ms): Run: git rev-parse --show-cdup
[2025-11-05T11:36:29.988Z] Start: Run: podman ps -q -a --filter label=devcontainer.local_folder=/Users/user/Projects/test --filter label=devcontainer.config_file=/Users/user/Projects/test/.devcontainer/devcontainer.json
[2025-11-05T11:36:30.054Z] Stop (66 ms): Run: podman ps -q -a --filter label=devcontainer.local_folder=/Users/user/Projects/test --filter label=devcontainer.config_file=/Users/user/Projects/test/.devcontainer/devcontainer.json
[2025-11-05T11:36:30.055Z] Start: Run: podman inspect --type image mcr.microsoft.com/devcontainers/base:bullseye
[2025-11-05T11:36:30.133Z] Stop (78 ms): Run: podman inspect --type image mcr.microsoft.com/devcontainers/base:bullseye
[2025-11-05T11:36:30.134Z] Resolving Feature dependencies for 'ghcr.io/devcontainers/features/common-utils:2'...
[2025-11-05T11:36:30.135Z] * Processing feature: ghcr.io/devcontainers/features/common-utils:2
[2025-11-05T11:36:30.135Z] Loading 16 extra certificates from /var/folders/97/3vfx2sds69q5rqsk1q7hnmq80000gn/T/vsch/certificates-c8745a5f0ab856b8cd536dff98ecc2ff903278eb35649193b277161fe8a60bcd.pem.
[2025-11-05T11:36:30.334Z] Start: Run: docker-credential-osxkeychain get
[2025-11-05T11:36:30.336Z] Stop (2 ms): Run: docker-credential-osxkeychain get
[2025-11-05T11:36:30.338Z] Stop (4 ms): Run: docker-credential-osxkeychain get
[2025-11-05T11:36:30.681Z] Resolving Feature dependencies for 'ghcr.io/stuartleeks/dev-container-features/shell-history:0'...
[2025-11-05T11:36:30.681Z] * Processing feature: ghcr.io/stuartleeks/dev-container-features/shell-history:0
[2025-11-05T11:36:30.912Z] * Processing feature: ghcr.io/devcontainers/features/common-utils
[2025-11-05T11:36:31.114Z] * Processing feature: ghcr.io/meaningful-ooo/devcontainer-features/fish
[2025-11-05T11:36:31.320Z] Soft-dependency 'ghcr.io/meaningful-ooo/devcontainer-features/fish' is not required.  Removing from installation order...
[2025-11-05T11:36:31.321Z] * Fetching feature: common-utils_0_oci
[2025-11-05T11:36:31.561Z] Files to omit: ''
[2025-11-05T11:36:31.569Z] * Fetched feature: common-utils_0_oci version 2.5.4
[2025-11-05T11:36:31.569Z] * Fetching feature: shell-history_1_oci
[2025-11-05T11:36:31.792Z] Files to omit: ''
[2025-11-05T11:36:31.794Z] * Fetched feature: shell-history_1_oci version 0.0.6
[2025-11-05T11:36:31.798Z] Start: Run: podman buildx build --load --build-context dev_containers_feature_content_source=/var/folders/97/3vfx2sds69q5rqsk1q7hnmq80000gn/T/devcontainercli/container-features/0.80.1-1762342590134 --build-arg _DEV_CONTAINERS_BASE_IMAGE=mcr.microsoft.com/devcontainers/base:bullseye --build-arg _DEV_CONTAINERS_IMAGE_USER=root --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp --target dev_containers_target_stage -f /var/folders/97/3vfx2sds69q5rqsk1q7hnmq80000gn/T/devcontainercli/container-features/0.80.1-1762342590134/Dockerfile.extended -t vsc-test-1ac7854556e4aca4c82e6fb49f71ead35612cf9232f166ce339da8bdd9dbcf9f-features /Users/user/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/data/empty-folder
[2025-11-05T11:36:31.910Z] [1/2] STEP 1/4: FROM mcr.microsoft.com/devcontainers/base:bullseye AS dev_containers_feature_content_normalize
[2025-11-05T11:36:32.187Z] [1/2] STEP 2/4: USER root
[2025-11-05T11:36:32.208Z] --> 12c35cc7ba05
[2025-11-05T11:36:32.210Z] [1/2] STEP 3/4: COPY --from=dev_containers_feature_content_source devcontainer-features.builtin.env /tmp/build-features/
[2025-11-05T11:36:32.292Z] --> 6ee35c94760e
[2025-11-05T11:36:32.294Z] [1/2] STEP 4/4: RUN chmod -R 0755 /tmp/build-features/
[2025-11-05T11:36:32.418Z] --> 0542fa61f8eb
[2025-11-05T11:36:32.419Z] [2/2] STEP 1/10: FROM mcr.microsoft.com/devcontainers/base:bullseye AS dev_containers_target_stage
[2025-11-05T11:36:32.666Z] [2/2] STEP 2/10: USER root
[2025-11-05T11:36:32.671Z] --> Using cache 12c35cc7ba051d0799be445829f1b1683c0fd0bd4dc3a3e662b4236cbb863054
--> 12c35cc7ba05
[2025-11-05T11:36:32.677Z] [2/2] STEP 3/10: RUN mkdir -p /tmp/dev-container-features
[2025-11-05T11:36:32.852Z] --> 914c65e6494b
[2025-11-05T11:36:32.854Z] [2/2] STEP 4/10: COPY --from=dev_containers_feature_content_normalize /tmp/build-features/ /tmp/dev-container-features
[2025-11-05T11:36:32.920Z] --> af44d89d2f51
[2025-11-05T11:36:32.922Z] [2/2] STEP 5/10: RUN echo "_CONTAINER_USER_HOME=$( (command -v getent >/dev/null 2>&1 && getent passwd 'root' || grep -E '^root|^[^:]*:[^:]*:root:' /etc/passwd || true) | cut -d: -f6)" >> /tmp/dev-container-features/devcontainer-features.builtin.env && echo "_REMOTE_USER_HOME=$( (command -v getent >/dev/null 2>&1 && getent passwd 'vscode' || grep -E '^vscode|^[^:]*:[^:]*:vscode:' /etc/passwd || true) | cut -d: -f6)" >> /tmp/dev-container-features/devcontainer-features.builtin.env
[2025-11-05T11:36:33.048Z] --> 77eb544157ec
[2025-11-05T11:36:33.049Z] [2/2] STEP 6/10: RUN --mount=type=bind,from=dev_containers_feature_content_source,source=common-utils_0,target=/tmp/build-features-src/common-utils_0     cp -ar /tmp/build-features-src/common-utils_0 /tmp/dev-container-features  && chmod -R 0755 /tmp/dev-container-features/common-utils_0  && cd /tmp/dev-container-features/common-utils_0  && chmod +x ./devcontainer-features-install.sh  && ./devcontainer-features-install.sh  && rm -rf /tmp/dev-container-features/common-utils_0
[2025-11-05T11:36:33.151Z] cp: cannot access '/tmp/build-features-src/common-utils_0': Permission denied
[2025-11-05T11:36:33.169Z] Error: building at STEP "RUN --mount=type=bind,from=dev_containers_feature_content_source,source=common-utils_0,target=/tmp/build-features-src/common-utils_0 cp -ar /tmp/build-features-src/common-utils_0 /tmp/dev-container-features  && chmod -R 0755 /tmp/dev-container-features/common-utils_0  && cd /tmp/dev-container-features/common-utils_0  && chmod +x ./devcontainer-features-install.sh  && ./devcontainer-features-install.sh  && rm -rf /tmp/dev-container-features/common-utils_0": while running runtime: exit status 1

[2025-11-05T11:36:33.172Z] Stop (1374 ms): Run: podman buildx build --load --build-context dev_containers_feature_content_source=/var/folders/97/3vfx2sds69q5rqsk1q7hnmq80000gn/T/devcontainercli/container-features/0.80.1-1762342590134 --build-arg _DEV_CONTAINERS_BASE_IMAGE=mcr.microsoft.com/devcontainers/base:bullseye --build-arg _DEV_CONTAINERS_IMAGE_USER=root --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp --target dev_containers_target_stage -f /var/folders/97/3vfx2sds69q5rqsk1q7hnmq80000gn/T/devcontainercli/container-features/0.80.1-1762342590134/Dockerfile.extended -t vsc-test-1ac7854556e4aca4c82e6fb49f71ead35612cf9232f166ce339da8bdd9dbcf9f-features /Users/user/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/data/empty-folder
[2025-11-05T11:36:33.172Z] Error: Command failed: podman buildx build --load --build-context dev_containers_feature_content_source=/var/folders/97/3vfx2sds69q5rqsk1q7hnmq80000gn/T/devcontainercli/container-features/0.80.1-1762342590134 --build-arg _DEV_CONTAINERS_BASE_IMAGE=mcr.microsoft.com/devcontainers/base:bullseye --build-arg _DEV_CONTAINERS_IMAGE_USER=root --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp --target dev_containers_target_stage -f /var/folders/97/3vfx2sds69q5rqsk1q7hnmq80000gn/T/devcontainercli/container-features/0.80.1-1762342590134/Dockerfile.extended -t vsc-test-1ac7854556e4aca4c82e6fb49f71ead35612cf9232f166ce339da8bdd9dbcf9f-features /Users/user/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/data/empty-folder
[2025-11-05T11:36:33.173Z]     at w6 (/Users/user/.vscode/extensions/ms-vscode-remote.remote-containers-0.427.0/dist/spec-node/devContainersSpecCLI.js:467:1253)
[2025-11-05T11:36:33.173Z]     at ax (/Users/user/.vscode/extensions/ms-vscode-remote.remote-containers-0.427.0/dist/spec-node/devContainersSpecCLI.js:467:997)
[2025-11-05T11:36:33.173Z]     at async Y6 (/Users/user/.vscode/extensions/ms-vscode-remote.remote-containers-0.427.0/dist/spec-node/devContainersSpecCLI.js:484:3842)
[2025-11-05T11:36:33.173Z]     at async BC (/Users/user/.vscode/extensions/ms-vscode-remote.remote-containers-0.427.0/dist/spec-node/devContainersSpecCLI.js:484:4957)
[2025-11-05T11:36:33.173Z]     at async p7 (/Users/user/.vscode/extensions/ms-vscode-remote.remote-containers-0.427.0/dist/spec-node/devContainersSpecCLI.js:665:202)
[2025-11-05T11:36:33.173Z]     at async d7 (/Users/user/.vscode/extensions/ms-vscode-remote.remote-containers-0.427.0/dist/spec-node/devContainersSpecCLI.js:664:14804)
[2025-11-05T11:36:33.173Z]     at async /Users/user/.vscode/extensions/ms-vscode-remote.remote-containers-0.427.0/dist/spec-node/devContainersSpecCLI.js:484:1188
[2025-11-05T11:36:33.179Z] Stop (3385 ms): Run: /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin) /Users/user/.vscode/extensions/ms-vscode-remote.remote-containers-0.427.0/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /Users/user/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --docker-path podman --container-session-data-folder /tmp/devcontainers-2459b8e5-1ad1-4dc2-aa8c-239e774836491762342588983 --workspace-folder /Users/user/Projects/test --workspace-mount-consistency cached --gpu-availability detect --id-label devcontainer.local_folder=/Users/user/Projects/test --id-label devcontainer.config_file=/Users/user/Projects/test/.devcontainer/devcontainer.json --log-level debug --log-format json --config /Users/user/Projects/test/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root --include-configuration --include-merged-configuration
[2025-11-05T11:36:33.179Z] Exit code 1
[2025-11-05T11:36:33.182Z] Command failed: /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin) /Users/user/.vscode/extensions/ms-vscode-remote.remote-containers-0.427.0/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /Users/user/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --docker-path podman --container-session-data-folder /tmp/devcontainers-2459b8e5-1ad1-4dc2-aa8c-239e774836491762342588983 --workspace-folder /Users/user/Projects/test --workspace-mount-consistency cached --gpu-availability detect --id-label devcontainer.local_folder=/Users/user/Projects/test --id-label devcontainer.config_file=/Users/user/Projects/test/.devcontainer/devcontainer.json --log-level debug --log-format json --config /Users/user/Projects/test/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root --include-configuration --include-merged-configuration
[2025-11-05T11:36:33.182Z] Exit code 1
```

Tried also with rootful podman, same issue.
