### ISSUE TITLE
devcontainer up: Error: Command failed due to # syntax=docker/dockerfile:1.4

### ISSUE THREAD

**Issue by alunduil** [devcontainers/cli#549]
# Prerequisites

```
devcontainer --version
0.42.0
```

```
docker version
Client: Docker Engine - Community
 Cloud integration: v1.0.33
 Version:           24.0.2
 API version:       1.43
 Go version:        go1.20.4
 Git commit:        cb74dfc
 Built:             Thu May 25 21:52:17 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.2
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.4
  Git commit:       659604f
  Built:            Thu May 25 21:52:17 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.21
  GitCommit:        3dce8eb055cbb6872793272b4f20ed16117344f8
 runc:
  Version:          1.1.7
  GitCommit:        v1.1.7-0-g860f061
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

## devcontainer.json

```jsonc
{
        "name": "experiment",
        "image": "mcr.microsoft.com/devcontainers/base:debian",

        "features": {
                "ghcr.io/devcontainers/features/git:1": {},
                "ghcr.io/devcontainers/features/github-cli:1": {},
                "ghcr.io/devcontainers/features/python:1": {},
                "ghcr.io/devcontainers-contrib/features/poetry:2": {}
        },

        // Use 'forwardPorts' to make a list of ports inside the container available locally.
        // "forwardPorts": [],

        // Use 'postCreateCommand' to run commands after the container is created.
        "postCreateCommand": "poetry install",

        // Configure tool-specific properties.
        "customizations": {
                "vscode": {
                        "settings": {
                                "python.analysis.typeCheckingMode": "basic",
                                "python.pythonPath": "${workspaceFolder}/.venv/bin/python",
                                "python.linting.pylintPath": "${workspaceFolder}/.venv/bin/pylint",
                                "python.testing.pytestArgs": [
                                        "--no-cov", "templatise_test"
                                ],
                                "python.testing.unittestEnabled": false,
                                "python.testing.pytestEnabled": true
                        },
                        "extensions": [
                                "GitHub.vscode-pull-request-github",
                                "eamodio.gitlens",
                                "ms-azuretools.vscode-docker",
                                "DavidAnson.vscode-markdownlint",
                                "tamasfe.even-better-toml"
                        ]
                }
        },

        // Uncomment to connect as root instead. More info: https://aka.ms/dev-containers-non-root.
        "remoteUser": "vscode"
}
```

# How to reproduce

1. Create empty directory with aforementioned devcontainer.json at ${PWD}/.devcontainer/devcontainer.json
2. Run: `devcontainer up`

I expect this is something from my environment leading to this so troubleshooting assistance to track down why I'm hitting this would be greatly appreciated.

I can confirm that removing the `# syntax=docker/dockerfile:1.4` line from Dockerfile.extended does allow devcontainer up to complete successfully but I have not verified the container is usable.

# Expected outcome

Working devcontainer build that I can use with VS Code.

# Actual outcome

Error during feature initialisation on Dockerfile.extended's use of syntax:

```
[4678 ms] Start: Run: docker buildx build --load --build-context dev_containers_feature_content_source=/tmp/devcontainercli-alunduil/container-features/0.42.0-1686482542764 --build-arg _DEV_CONTAINERS_BASE_IMAGE=mcr.microsoft.com/devcontainers/base:debian --build-arg _DEV_CONTAINERS_IMAGE_USER=root --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp --target dev_containers_target_stage -t vsc-devcontainer-755a81158a18280d694bd5eaf49a4f6063d194b28e4234601df8b32a7bdbc90e-features -f /tmp/devcontainercli-alunduil/container-features/0.42.0-1686482542764/Dockerfile.extended /tmp/devcontainercli-alunduil/empty-folder
[+] Building 1.7s (4/4) FINISHED                                                
 => [internal] load build definition from Dockerfile.extended              0.3s
 => => transferring dockerfile: 4.55kB                                     0.0s
 => [internal] load .dockerignore                                          0.3s
 => => transferring context: 2B                                            0.0s
 => resolve image config for docker.io/docker/dockerfile:1.4               0.0s
 => CACHED docker-image://docker.io/docker/dockerfile:1.4                  0.0s
Dockerfile.extended:1
--------------------
   1 | >>> # syntax=docker/dockerfile:1.4
   2 |     ARG _DEV_CONTAINERS_BASE_IMAGE=placeholder
   3 |     
--------------------
ERROR: failed to solve: exit code: 1
Error: Command failed: docker buildx build --load --build-context dev_containers_feature_content_source=/tmp/devcontainercli-alunduil/container-features/0.42.0-1686482542764 --build-arg _DEV_CONTAINERS_BASE_IMAGE=mcr.microsoft.com/devcontainers/base:debian --build-arg _DEV_CONTAINERS_IMAGE_USER=root --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp --target dev_containers_target_stage -t vsc-devcontainer-755a81158a18280d694bd5eaf49a4f6063d194b28e4234601df8b32a7bdbc90e-features -f /tmp/devcontainercli-alunduil/container-features/0.42.0-1686482542764/Dockerfile.extended /tmp/devcontainercli-alunduil/empty-folder
    at mte (/home/alunduil/.vscode/extensions/ms-vscode-remote.remote-containers-0.295.0/dist/spec-node/devContainersSpecCLI.js:2003:3286)
    at IN (/home/alunduil/.vscode/extensions/ms-vscode-remote.remote-containers-0.295.0/dist/spec-node/devContainersSpecCLI.js:2003:3222)
    at async Ote (/home/alunduil/.vscode/extensions/ms-vscode-remote.remote-containers-0.295.0/dist/spec-node/devContainersSpecCLI.js:2020:3660)
    at async Hf (/home/alunduil/.vscode/extensions/ms-vscode-remote.remote-containers-0.295.0/dist/spec-node/devContainersSpecCLI.js:2020:4775)
    at async Qre (/home/alunduil/.vscode/extensions/ms-vscode-remote.remote-containers-0.295.0/dist/spec-node/devContainersSpecCLI.js:2151:10371)
    at async Zre (/home/alunduil/.vscode/extensions/ms-vscode-remote.remote-containers-0.295.0/dist/spec-node/devContainersSpecCLI.js:2151:10112)
{"outcome":"error","message":"Command failed: docker buildx build --load --build-context dev_containers_feature_content_source=/tmp/devcontainercli-alunduil/container-features/0.42.0-1686482542764 --build-arg _DEV_CONTAINERS_BASE_IMAGE=mcr.microsoft.com/devcontainers/base:debian --build-arg _DEV_CONTAINERS_IMAGE_USER=root --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp --target dev_containers_target_stage -t vsc-devcontainer-755a81158a18280d694bd5eaf49a4f6063d194b28e4234601df8b32a7bdbc90e-features -f /tmp/devcontainercli-alunduil/container-features/0.42.0-1686482542764/Dockerfile.extended /tmp/devcontainercli-alunduil/empty-folder","description":"An error occurred setting up the container."}
```

# References

* [full output from devcontainer up](https://gist.github.com/alunduil/94ecbee4eae6753455fee8faaee60834)

**Comment by alunduil** [comment]
Playing around with this, if I use `devcontainer up --buildkit=never` it also succeeds.  The question then becomes what is wrong with my buildkit installation if anything and how can I force this option to be used in VS Code for devcontainer building?

**Comment by chrmarti** [comment]
What do you get for running `docker buildx version`?

**Comment by chrmarti** [comment]
Does it work when you change the default builder back to `default`?

**Comment by alunduil** [comment]
@chrmarti I can confirm that changing back to default does result in the error I mentioned in my original description of the problem.  I can also confirm that switching back to the vscode builder results in a new error message (likely due to changes in the python feature itself show below). Feel free to let me know if there is anything else I can try or provide.  I'm happy to troubleshoot deeper on my own, but I still need to grasp how to do that.

```
#0 53.05 Installing Python tools...
#0 53.24 Updating pip...
#0 53.59 error: externally-managed-environment
#0 53.59 
#0 53.59 × This environment is externally managed
#0 53.59 ╰─> To install Python packages system-wide, try apt install
#0 53.59     python3-xyz, where xyz is the package you are trying to
#0 53.59     install.
#0 53.59     
#0 53.59     If you wish to install a non-Debian-packaged Python package,
#0 53.59     create a virtual environment using python3 -m venv path/to/venv.
#0 53.59     Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
#0 53.59     sure you have python3-full installed.
#0 53.59     
#0 53.59     If you wish to install a non-Debian packaged Python application,
#0 53.59     it may be easiest to use pipx install xyz, which will manage a
#0 53.59     virtual environment for you. Make sure you have pipx installed.
#0 53.59     
#0 53.59     See /usr/share/doc/python3.11/README.venv for more information.
#0 53.59 
#0 53.59 note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
#0 53.59 hint: See PEP 668 for the detailed specification.
#0 53.66 ERROR: Feature "Python" (ghcr.io/devcontainers/features/python) failed to install! Look at the documentation at https://github.com/devcontainers/features/tree/main/src/python for help troubleshooting this error.
```

**Comment by chrmarti** [comment]
Could you open a new issue for https://github.com/devcontainers/features for the Python install problem?

The error about `# syntax=docker/dockerfile:1.4` could also indicate an issue with your Docker installation, maybe check if you are on the latest version and try running `docker pull docker/dockerfile:1.4` to make sure that image is up to date too.

**Comment by alunduil** [comment]
https://github.com/devcontainers/features/issues/222 is already tracking the discovered os-provided Python feature issue.  I'll let the discussion continue in that issue as specifying the version to latest works for my purposes and allows me to focus on this buggy behaviour.

**Comment by alunduil** [comment]
I don't see this anymore with updated versions. I'm closing but if it comes up for anyone else please reopen.
