### ISSUE TITLE
docker compose

### ISSUE THREAD

**Issue by Gnoale** [devcontainers/cli#574]
Hello, 

You might want to update your `docker-compose` path to `docker compose` in the relevant files ?
I changed it manually in `/usr/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js` to overcome this issue

```
16:01 $ devcontainer up --workspace-folder .
[2 ms] @devcontainers/cli 0.47.0. Node.js v16.19.1. linux 5.4.0-152-generic x64.
[588 ms] Start: Run: docker-compose -f /home/hum/git/some/path/.devcontainer/docker-compose.yml config
[1236 ms] 
[1236 ms] Version in "/home/hum/git/some/path/.devcontainer/docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/

[1236 ms] Exit code 1
Error: Command failed: docker-compose -f /home/hum/git/some/path/.devcontainer/docker-compose.yml config
    at Sl (/usr/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:2005:889)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async kte (/usr/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:1972:1370)
    at async _te (/usr/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:1954:3170)
    at async Qte (/usr/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:2024:3833)
    at async Kf (/usr/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:2024:4775)
    at async xne (/usr/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:2156:12125)
    at async wne (/usr/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:2156:11866)
{"outcome":"error","message":"Command failed: docker-compose -f /home/hum/git/some/path/.devcontainer/docker-compose.yml config","description":"An error occurred retrieving the Docker Compose configuration."}
```

**Comment by chrmarti** [comment]
You can uninstall `docker-compose`, we will automatically use `docker compose` then.
