### ISSUE TITLE
chown: changing ownership of '/home/vscode': Invalid argument

### ISSUE THREAD

**Issue by lmilbaum** [devcontainers/cli#587]
Container build is failing. Stdout is too large to be captured in VSCode terminal.
The error is not clear enough. 

RHEL 8
SELinux disabled
podman
vscode extension

devcontainer.json
```
{
    "name": "gitlab-runners",
    "image": "mcr.microsoft.com/devcontainers/base:debian-11"
}
```

partial log
```
chown: changing ownership of '/home/vscode/.oh-my-zsh/tools': Invalid argument
chown: changing ownership of '/home/vscode/.oh-my-zsh': Invalid argument
chown: changing ownership of '/home/vscode/.profile': Invalid argument
chown: changing ownership of '/home/vscode/.zshrc': Invalid argument
chown: changing ownership of '/home/vscode': Invalid argument
Error: building at STEP "RUN eval $(sed -n "s/${REMOTE_USER}:[^:]*:\([^:]*\):\([^:]*\):[^:]*:\([^:]*\).*/OLD_UID=\1;OLD_GID=\2;HOME_FOLDER=\3/p" /etc/passwd);        eval $(sed -n "s/\([^:]*\):[^:]*:${NEW_UID}:.*/EXISTING_USER=\1/p" /etc/passwd);        eval $(sed -n "s/\([^:]*\):[^:]*:${NEW_GID}:.*/EXISTING_GROUP=\1/p" /etc/group);      if [ -z "$OLD_UID" ]; then              echo "Remote user not found in /etc/passwd ($REMOTE_USER).";    elif [ "$OLD_UID" = "$NEW_UID" -a "$OLD_GID" = "$NEW_GID" ]; then             echo "UIDs and GIDs are the same ($NEW_UID:$NEW_GID).";         elif [ "$OLD_UID" != "$NEW_UID" -a -n "$EXISTING_USER" ]; then                echo "User with UID exists ($EXISTING_USER=$NEW_UID).";         elif [ "$OLD_GID" != "$NEW_GID" -a -n "$EXISTING_GROUP" ]; then               echo "Group with GID exists ($EXISTING_GROUP=$NEW_GID).";       else            echo "Updating UID:GID from $OLD_UID:$OLD_GID to $NEW_UID:$NEW_GID.";                 sed -i -e "s/\(${REMOTE_USER}:[^:]*:\)[^:]*:[^:]*/\1${NEW_UID}:${NEW_GID}/" /etc/passwd;                if [ "$OLD_GID" != "$NEW_GID" ]; then                         sed -i -e "s/\([^:]*:[^:]*:\)${OLD_GID}:/\1${NEW_GID}:/" /etc/group;            fi;             chown -R $NEW_UID:$NEW_GID $HOME_FOLDER;      fi;": while running runtime: exit status 1
[2325 ms] Error: Command failed: docker build -f /tmp/devcontainercli-lmilbaum/updateUID.Dockerfile-0.42.0 -t vsc-gitlab-runners-85bc48f0532c0d75af7fb978be19442f30e7386b4807fbf233ffa2bdfcd5f7c5-uid --build-arg BASE_IMAGE=mcr.microsoft.com/devcontainers/base:debian-11 --build-arg REMOTE_USER=vscode --build-arg NEW_UID=114164 --build-arg NEW_GID=114164 --build-arg IMAGE_USER=root /home/lmilbaum/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/data/empty-folder
[2325 ms]     at mte (/home/lmilbaum/.vscode/extensions/ms-vscode-remote.remote-containers-0.295.0/dist/spec-node/devContainersSpecCLI.js:2003:3286)
[2325 ms]     at IN (/home/lmilbaum/.vscode/extensions/ms-vscode-remote.remote-containers-0.295.0/dist/spec-node/devContainersSpecCLI.js:2003:3222)
[2325 ms]     at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
[2325 ms]     at async Ote (/home/lmilbaum/.vscode/extensions/ms-vscode-remote.remote-containers-0.295.0/dist/spec-node/devContainersSpecCLI.js:2020:3660)
[2325 ms]     at async Hf (/home/lmilbaum/.vscode/extensions/ms-vscode-remote.remote-containers-0.295.0/dist/spec-node/devContainersSpecCLI.js:2020:4775)
[2325 ms]     at async Qre (/home/lmilbaum/.vscode/extensions/ms-vscode-remote.remote-containers-0.295.0/dist/spec-node/devContainersSpecCLI.js:2151:10371)
[2325 ms]     at async Zre (/home/lmilbaum/.vscode/extensions/ms-vscode-remote.remote-containers-0.295.0/dist/spec-node/devContainersSpecCLI.js:2151:10112)
[2329 ms] Exit code 1
[2331 ms] Command failed: /usr/share/code/code --ms-enable-electron-run-as-node /home/lmilbaum/.vscode/extensions/ms-vscode-remote.remote-containers-0.295.0/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /home/lmilbaum/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --container-session-data-folder /tmp/devcontainers-ed923ed4-949f-450f-b766-b6e12a37630b1688556041270 --workspace-folder /home/lmilbaum/repos/github.com/platform-engineering-org/gitlab-runners --workspace-mount-consistency cached --id-label devcontainer.local_folder=/home/lmilbaum/repos/github.com/platform-engineering-org/gitlab-runners --id-label devcontainer.config_file=/home/lmilbaum/repos/github.com/platform-engineering-org/gitlab-runners/.devcontainer/devcontainer.json --log-level debug --log-format json --config /home/lmilbaum/repos/github.com/platform-engineering-org/gitlab-runners/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
```

**Comment by chrmarti** [comment]
Try adding `"updateRemoteUserUID": false` to the devcontainer.json, that will turn off the failing step.

Also see https://code.visualstudio.com/remote/advancedcontainers/docker-options#_podman for information on using Dev Containers with Podman.
