### ISSUE TITLE
Question: No meaningful error log can be printed/presisted if `postStartCommand` fails

### ISSUE THREAD

**Issue by axmmisaka** [devcontainers/cli#600]
Our project is experiencing nondeterministic failures of `postStartCommand`, and we would like to dig up the logs to investigate what happened during the container creation process. 

What I discovered is that, if `postStartCommand` failed, no log will be printed to stdout/stderr. The only thing I could see is:
```
2023-07-22 20:09:30.605Z: /bin/bash -i ./utils/scripts/setup-lf.bash nightly
2023-07-22 20:09:31.093Z: postStartCommand failed with exit code 127. Skipping any further user-provided commands.

2023-07-22 20:09:31.099Z: Error: Command failed: /bin/bash -i ./utils/scripts/setup-lf.bash nightly
2023-07-22 20:09:31.100Z:     at k8 (/usr/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:1780:130)
2023-07-22 20:09:31.100Z:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-07-22 20:09:31.100Z:     at async W0 (/usr/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:1772:4434)
2023-07-22 20:09:31.101Z:     at async F8 (/usr/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:1772:3951)
2023-07-22 20:09:31.101Z:     at async z0 (/usr/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:1772:3143)
2023-07-22 20:09:31.102Z:     at async Xa (/usr/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:1772:2427)
2023-07-22 20:09:31.102Z:     at async Lte (/usr/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:2007:1346)
2023-07-22 20:09:31.102Z:     at async e3 (/usr/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:2007:964)
2023-07-22 20:09:31.103Z:     at async Qte (/usr/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:2024:3660)
2023-07-22 20:09:31.103Z:     at async Kf (/usr/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:2024:4775)
2023-07-22 20:09:31.107Z: {"outcome":"error","message":"Command failed: /bin/bash -i ./utils/scripts/setup-lf.bash nightly","description":"The postStartCommand in the devcontainer.json failed.","containerId":"2cf9dbd367288fbeaca871a0f68637bbe68a6861dd9b2d4ca1f87d8f82994e24"}
2023-07-22 20:09:31.235Z: devcontainer process exited with exit code 1
```

As we are using codespaces, one way I discovered that could potentially work is to redirect stdout and stderr to persistent storage, and access them after the recovery is created.
```
    "postStartCommand": {
        "setup-user-env": "bash -i ./utils/scripts/setup-user-env.bash >> /workspaces/.codespaces/.persistedshare/stdout-env.log 2>>/workspaces/.codespaces/.persistedshare/stderr-env.log",
        "setup-lf": "bash ./utils/scripts/setup-lf.bash nightly >> /workspaces/.codespaces/.persistedshare/stdout-lf.log 2>>/workspaces/.codespaces/.persistedshare/stderr-lf.log"
    },
```

Yet, with `devcontainers/ci`, this is not possible as `/mnt/github` will be removed if `devcontainer up` fails.

I wonder if there is any way to redirect the output of `postStartCommand` to stdout of `devcontainer-cli`, so that debugging would be much easier.

My `devcontainer.json`:
https://github.com/lf-lang/playground-lingua-franca/blob/d42fb3bb16bf12bde59f22764a4e38f72a2d4356/.devcontainer/devcontainer.json

**Comment by chrmarti** [comment]
Duplicate of https://github.com/devcontainers/cli/issues/845
