### ISSUE TITLE
Remote host dev container: Command failed: docker build -f /tmp/devcontainercli

### ISSUE THREAD

**Issue by naturedamends** [devcontainers/cli#625]
I'm on a macos host. Running vscode in remote host. Within a vm, then running opening the dev container within the remote host.

Happy to help in anyway, just let me know

You can create an identical virtual machine using multipass and the following cloud init
```
users:
  - default
  - name: vmuser
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
    - ssh-ed25519 -----
groups:
- docker
snap:
  commands:
  - [install, docker]
runcmd:
- adduser vmuser docker
- reboot
```

```
[2023-08-26T07:01:37.740Z] Dev Containers 0.304.0 in VS Code 1.81.1 (6c3e3dba23e8fadc360aed75ce363ba185c49794).
[2023-08-26T07:01:37.740Z] Start: Resolving Remote
[2023-08-26T07:01:37.749Z] Start: Run: ssh 192.168.64.134 /bin/sh
[2023-08-26T07:01:37.754Z] Start: Run in host: id -un
[2023-08-26T07:01:38.034Z] vmuser
[2023-08-26T07:01:38.034Z] 
[2023-08-26T07:01:38.034Z] Stop (280 ms): Run in host: id -un
[2023-08-26T07:01:38.034Z] Start: Run in host: getent passwd vmuser
[2023-08-26T07:01:38.038Z] Stop (4 ms): Run in host: getent passwd vmuser
[2023-08-26T07:01:38.039Z] Start: Run in host: echo ~
[2023-08-26T07:01:38.042Z] /home/vmuser
[2023-08-26T07:01:38.042Z] 
[2023-08-26T07:01:38.042Z] Stop (3 ms): Run in host: echo ~
[2023-08-26T07:01:38.042Z] Start: Run in host: test -x '/home/vmuser/.vscode-remote-containers/bin/6c3e3dba23e8fadc360aed75ce363ba185c49794/node'
[2023-08-26T07:01:38.047Z] 
[2023-08-26T07:01:38.047Z] 
[2023-08-26T07:01:38.048Z] Exit code 1
[2023-08-26T07:01:38.048Z] Stop (6 ms): Run in host: test -x '/home/vmuser/.vscode-remote-containers/bin/6c3e3dba23e8fadc360aed75ce363ba185c49794/node'
[2023-08-26T07:01:38.048Z] Start: Run in host: test -x '/home/vmuser/.vscode-server/bin/6c3e3dba23e8fadc360aed75ce363ba185c49794/node'
[2023-08-26T07:01:38.051Z] 
[2023-08-26T07:01:38.051Z] 
[2023-08-26T07:01:38.051Z] Stop (3 ms): Run in host: test -x '/home/vmuser/.vscode-server/bin/6c3e3dba23e8fadc360aed75ce363ba185c49794/node'
[2023-08-26T07:01:38.052Z] Start: Run in host: test -f '/home/vmuser/.vscode-server/bin/6c3e3dba23e8fadc360aed75ce363ba185c49794/node_modules/node-pty/package.json'
[2023-08-26T07:01:38.055Z] 
[2023-08-26T07:01:38.055Z] 
[2023-08-26T07:01:38.055Z] Stop (3 ms): Run in host: test -f '/home/vmuser/.vscode-server/bin/6c3e3dba23e8fadc360aed75ce363ba185c49794/node_modules/node-pty/package.json'
[2023-08-26T07:01:38.055Z] Start: Run in host: test -f '/home/vmuser/.vscode-remote-containers/dist/vscode-remote-containers-server-0.304.0.js'
[2023-08-26T07:01:38.058Z] 
[2023-08-26T07:01:38.059Z] 
[2023-08-26T07:01:38.059Z] Stop (4 ms): Run in host: test -f '/home/vmuser/.vscode-remote-containers/dist/vscode-remote-containers-server-0.304.0.js'
[2023-08-26T07:01:38.063Z] userEnvProbe: loginInteractiveShell (default)
[2023-08-26T07:01:38.063Z] userEnvProbe: not found in cache
[2023-08-26T07:01:38.063Z] userEnvProbe shell: /bin/sh
[2023-08-26T07:01:38.252Z] userEnvProbe PATHs:
Probe:     '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin'
Container: None
[2023-08-26T07:01:38.257Z] Setting up container for folder or workspace: /home/vmuser/testing
[2023-08-26T07:01:38.257Z] Host: ssh://192.168.64.134
[2023-08-26T07:01:38.298Z] Start: Check Docker is running
[2023-08-26T07:01:38.298Z] Start: Run in Host: docker version --format {{.Server.APIVersion}}
[2023-08-26T07:01:38.513Z] Stop (215 ms): Run in Host: docker version --format {{.Server.APIVersion}}
[2023-08-26T07:01:38.513Z] Server API version: 1.41
[2023-08-26T07:01:38.514Z] Stop (216 ms): Check Docker is running
[2023-08-26T07:01:38.514Z] Start: Run in Host: docker volume ls -q
[2023-08-26T07:01:38.679Z] Stop (165 ms): Run in Host: docker volume ls -q
[2023-08-26T07:01:38.680Z] Start: Run in Host: docker ps -q -a --filter label=vsch.local.folder=/home/vmuser/testing --filter label=vsch.quality=stable
[2023-08-26T07:01:38.950Z] Stop (270 ms): Run in Host: docker ps -q -a --filter label=vsch.local.folder=/home/vmuser/testing --filter label=vsch.quality=stable
[2023-08-26T07:01:38.950Z] Start: Run in Host: docker ps -q -a --filter label=devcontainer.local_folder=/home/vmuser/testing --filter label=devcontainer.config_file=/home/vmuser/testing/.devcontainer/devcontainer.json
[2023-08-26T07:01:39.073Z] Stop (123 ms): Run in Host: docker ps -q -a --filter label=devcontainer.local_folder=/home/vmuser/testing --filter label=devcontainer.config_file=/home/vmuser/testing/.devcontainer/devcontainer.json
[2023-08-26T07:01:39.073Z] Start: Run in Host: docker ps -q -a --filter label=devcontainer.local_folder=/home/vmuser/testing
[2023-08-26T07:01:39.174Z] Stop (101 ms): Run in Host: docker ps -q -a --filter label=devcontainer.local_folder=/home/vmuser/testing
[2023-08-26T07:01:39.174Z] Start: Run in Host: docker ps -q -a --filter label=devcontainer.local_folder=/home/vmuser/testing
[2023-08-26T07:01:39.264Z] Stop (90 ms): Run in Host: docker ps -q -a --filter label=devcontainer.local_folder=/home/vmuser/testing
[2023-08-26T07:01:39.273Z] Start: Run in Host: /home/vmuser/.vscode-server/bin/6c3e3dba23e8fadc360aed75ce363ba185c49794/node /home/vmuser/.vscode-remote-containers/dist/dev-containers-cli-0.304.0/dist/spec-node/devContainersSpecCLI.js read-configuration --workspace-folder /home/vmuser/testing --id-label devcontainer.local_folder=/home/vmuser/testing --id-label devcontainer.config_file=/home/vmuser/testing/.devcontainer/devcontainer.json --log-level debug --log-format json --config /home/vmuser/testing/.devcontainer/devcontainer.json --mount-workspace-git-root true
[2023-08-26T07:01:39.557Z] @devcontainers/cli 0.50.0. Node.js v16.17.1. linux 5.15.0-79-generic x64.
[2023-08-26T07:01:39.557Z] Start: Run: git rev-parse --show-cdup
[2023-08-26T07:01:39.567Z] Stop (10 ms): Run: git rev-parse --show-cdup
[2023-08-26T07:01:39.569Z] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/home/vmuser/testing --filter label=devcontainer.config_file=/home/vmuser/testing/.devcontainer/devcontainer.json
[2023-08-26T07:01:39.699Z] Stop (130 ms): Run: docker ps -q -a --filter label=devcontainer.local_folder=/home/vmuser/testing --filter label=devcontainer.config_file=/home/vmuser/testing/.devcontainer/devcontainer.json
[2023-08-26T07:01:39.664Z] Stop (391 ms): Run in Host: /home/vmuser/.vscode-server/bin/6c3e3dba23e8fadc360aed75ce363ba185c49794/node /home/vmuser/.vscode-remote-containers/dist/dev-containers-cli-0.304.0/dist/spec-node/devContainersSpecCLI.js read-configuration --workspace-folder /home/vmuser/testing --id-label devcontainer.local_folder=/home/vmuser/testing --id-label devcontainer.config_file=/home/vmuser/testing/.devcontainer/devcontainer.json --log-level debug --log-format json --config /home/vmuser/testing/.devcontainer/devcontainer.json --mount-workspace-git-root true
[2023-08-26T07:01:39.673Z] Start: Run in Host: /home/vmuser/.vscode-server/bin/6c3e3dba23e8fadc360aed75ce363ba185c49794/node /home/vmuser/.vscode-remote-containers/dist/dev-containers-cli-0.304.0/dist/spec-node/devContainersSpecCLI.js up --container-session-data-folder /tmp/devcontainers-af369e26-aa8b-4551-ba2b-ef120643e0c31693033296421 --workspace-folder /home/vmuser/testing --workspace-mount-consistency cached --id-label devcontainer.local_folder=/home/vmuser/testing --id-label devcontainer.config_file=/home/vmuser/testing/.devcontainer/devcontainer.json --log-level debug --log-format json --config /home/vmuser/testing/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2023-08-26T07:01:39.940Z] @devcontainers/cli 0.50.0. Node.js v16.17.1. linux 5.15.0-79-generic x64.
[2023-08-26T07:01:39.940Z] Start: Run: docker buildx version
[2023-08-26T07:01:40.256Z] Stop (316 ms): Run: docker buildx version
[2023-08-26T07:01:40.257Z] github.com/docker/buildx v0.10.4 c513d34049e499c53468deac6c4267ee72948f02
[2023-08-26T07:01:40.257Z] 
[2023-08-26T07:01:40.258Z] Start: Resolving Remote
[2023-08-26T07:01:40.266Z] Start: Run: git rev-parse --show-cdup
[2023-08-26T07:01:40.272Z] Stop (6 ms): Run: git rev-parse --show-cdup
[2023-08-26T07:01:40.278Z] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/home/vmuser/testing --filter label=devcontainer.config_file=/home/vmuser/testing/.devcontainer/devcontainer.json
[2023-08-26T07:01:40.477Z] Stop (199 ms): Run: docker ps -q -a --filter label=devcontainer.local_folder=/home/vmuser/testing --filter label=devcontainer.config_file=/home/vmuser/testing/.devcontainer/devcontainer.json
[2023-08-26T07:01:40.480Z] Start: Run: docker inspect --type image mcr.microsoft.com/devcontainers/go:1-1.21-bullseye
[2023-08-26T07:01:40.635Z] Stop (155 ms): Run: docker inspect --type image mcr.microsoft.com/devcontainers/go:1-1.21-bullseye
[2023-08-26T07:01:41.724Z] local container features stored at: /home/vmuser/.vscode-remote-containers/dist/dev-containers-cli-0.304.0/dist/node_modules/vscode-dev-containers/container-features
[2023-08-26T07:01:41.727Z] Start: Run: tar --no-same-owner -x -f -
[2023-08-26T07:01:41.749Z] Stop (22 ms): Run: tar --no-same-owner -x -f -
[2023-08-26T07:01:41.760Z] Start: Run: docker build -f /tmp/devcontainercli-vmuser/updateUID.Dockerfile-0.50.0 -t vsc-testing-a657200756e273ad683c5fc254bcf3bcfc757c10e60fac109ba77ed794ef6226-uid --build-arg BASE_IMAGE=mcr.microsoft.com/devcontainers/go:1-1.21-bullseye --build-arg REMOTE_USER=vscode --build-arg NEW_UID=1000 --build-arg NEW_GID=1001 --build-arg IMAGE_USER=root /tmp/devcontainercli-vmuser/empty-folder
[2023-08-26T07:01:41.863Z] unable to prepare context: path "/tmp/devcontainercli-vmuser/empty-folder" not found
[2023-08-26T07:01:41.868Z] Stop (108 ms): Run: docker build -f /tmp/devcontainercli-vmuser/updateUID.Dockerfile-0.50.0 -t vsc-testing-a657200756e273ad683c5fc254bcf3bcfc757c10e60fac109ba77ed794ef6226-uid --build-arg BASE_IMAGE=mcr.microsoft.com/devcontainers/go:1-1.21-bullseye --build-arg REMOTE_USER=vscode --build-arg NEW_UID=1000 --build-arg NEW_GID=1001 --build-arg IMAGE_USER=root /tmp/devcontainercli-vmuser/empty-folder
[2023-08-26T07:01:41.818Z] Error: Command failed: docker build -f /tmp/devcontainercli-vmuser/updateUID.Dockerfile-0.50.0 -t vsc-testing-a657200756e273ad683c5fc254bcf3bcfc757c10e60fac109ba77ed794ef6226-uid --build-arg BASE_IMAGE=mcr.microsoft.com/devcontainers/go:1-1.21-bullseye --build-arg REMOTE_USER=vscode --build-arg NEW_UID=1000 --build-arg NEW_GID=1001 --build-arg IMAGE_USER=root /tmp/devcontainercli-vmuser/empty-folder
[2023-08-26T07:01:41.819Z]     at oAA (/home/vmuser/.vscode-remote-containers/dist/dev-containers-cli-0.304.0/dist/spec-node/devContainersSpecCLI.js:462:1066)
[2023-08-26T07:01:41.819Z]     at mK (/home/vmuser/.vscode-remote-containers/dist/dev-containers-cli-0.304.0/dist/spec-node/devContainersSpecCLI.js:462:1002)
[2023-08-26T07:01:41.819Z]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[2023-08-26T07:01:41.819Z]     at async mAA (/home/vmuser/.vscode-remote-containers/dist/dev-containers-cli-0.304.0/dist/spec-node/devContainersSpecCLI.js:479:3660)
[2023-08-26T07:01:41.819Z]     at async LC (/home/vmuser/.vscode-remote-containers/dist/dev-containers-cli-0.304.0/dist/spec-node/devContainersSpecCLI.js:479:4775)
[2023-08-26T07:01:41.819Z]     at async jeA (/home/vmuser/.vscode-remote-containers/dist/dev-containers-cli-0.304.0/dist/spec-node/devContainersSpecCLI.js:611:12219)
[2023-08-26T07:01:41.819Z]     at async _eA (/home/vmuser/.vscode-remote-containers/dist/dev-containers-cli-0.304.0/dist/spec-node/devContainersSpecCLI.js:611:11960)
[2023-08-26T07:01:41.825Z] Stop (2152 ms): Run in Host: /home/vmuser/.vscode-server/bin/6c3e3dba23e8fadc360aed75ce363ba185c49794/node /home/vmuser/.vscode-remote-containers/dist/dev-containers-cli-0.304.0/dist/spec-node/devContainersSpecCLI.js up --container-session-data-folder /tmp/devcontainers-af369e26-aa8b-4551-ba2b-ef120643e0c31693033296421 --workspace-folder /home/vmuser/testing --workspace-mount-consistency cached --id-label devcontainer.local_folder=/home/vmuser/testing --id-label devcontainer.config_file=/home/vmuser/testing/.devcontainer/devcontainer.json --log-level debug --log-format json --config /home/vmuser/testing/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2023-08-26T07:01:41.826Z] Exit code 1
[2023-08-26T07:01:41.830Z] Command failed: /home/vmuser/.vscode-server/bin/6c3e3dba23e8fadc360aed75ce363ba185c49794/node /home/vmuser/.vscode-remote-containers/dist/dev-containers-cli-0.304.0/dist/spec-node/devContainersSpecCLI.js up --container-session-data-folder /tmp/devcontainers-af369e26-aa8b-4551-ba2b-ef120643e0c31693033296421 --workspace-folder /home/vmuser/testing --workspace-mount-consistency cached --id-label devcontainer.local_folder=/home/vmuser/testing --id-label devcontainer.config_file=/home/vmuser/testing/.devcontainer/devcontainer.json --log-level debug --log-format json --config /home/vmuser/testing/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2023-08-26T07:01:41.830Z] Exit code 1
```

```
total 52
drwxrwxrwt 13 root   root   4096 Aug 26 08:02 .
drwxr-xr-x 19 root   root   4096 Aug 26 07:56 ..
drwxrwxrwt  2 root   root   4096 Aug 26 07:56 .ICE-unix
drwxrwxrwt  2 root   root   4096 Aug 26 07:56 .Test-unix
drwxrwxrwt  2 root   root   4096 Aug 26 07:56 .X11-unix
drwxrwxrwt  2 root   root   4096 Aug 26 07:56 .XIM-unix
drwxrwxrwt  2 root   root   4096 Aug 26 07:56 .font-unix
drwxrwxr-x  4 vmuser vmuser 4096 Aug 26 08:01 devcontainercli-vmuser
drwx------  4 root   root   4096 Aug 26 07:56 snap-private-tmp
drwx------  3 root   root   4096 Aug 26 07:56 systemd-private-f462e0174c054d0abc5eb21c4153f0c5-systemd-logind.service-AXA7Ip
drwx------  3 root   root   4096 Aug 26 07:56 systemd-private-f462e0174c054d0abc5eb21c4153f0c5-systemd-resolved.service-nZK1Af
drwx------  3 root   root   4096 Aug 26 07:56 systemd-private-f462e0174c054d0abc5eb21c4153f0c5-systemd-timesyncd.service-MBLiC5
drwxrwxr-x  2 vmuser vmuser 4096 Aug 26 08:01 vscode-typescript1000
$ ls -la /tmp/devcontainercli-vmuser
total 24
drwxrwxr-x  4 vmuser vmuser 4096 Aug 26 08:01 .
drwxrwxrwt 13 root   root   4096 Aug 26 08:02 ..
drwxrwxr-x  8 vmuser vmuser 4096 Aug 26 08:01 container-features
-rw-rw-r--  1 vmuser vmuser 2065 Aug 26 07:59 control-manifest.json
drwxrwxr-x  2 vmuser vmuser 4096 Aug 26 07:59 empty-folder
-rw-rw-r--  1 vmuser vmuser 1273 Aug 26 08:01 updateUID.Dockerfile-0.50.0
```

**Comment by chrmarti** [comment]
Not sure why it might not find `empty-folder` when it is there. Do you use any security tools that might interfere here? What type of filesystem is `/tmp` on?
```
unable to prepare context: path "/tmp/devcontainercli-vmuser/empty-folder" not found
```

**Comment by naturedamends** [comment]
> Not sure why it might not find `empty-folder` when it is there. Do you use any security tools that might interfere here? What type of filesystem is `/tmp` on?
> 
> ```
> unable to prepare context: path "/tmp/devcontainercli-vmuser/empty-folder" not found
> ```

Err, i'm not sure how to find out. I have changed nothing, just the default macos config. Its of one those hybrid filesystems, so it holds data in SSD and some in spinning drives.

Do you know a command to determine the if its different? I'm understanding is that its a normal file system, not a RAM or anything.

**Comment by naturedamends** [comment]
> Not sure why it might not find `empty-folder` when it is there. Do you use any security tools that might interfere here? What type of filesystem is `/tmp` on?
> 
> ```
> unable to prepare context: path "/tmp/devcontainercli-vmuser/empty-folder" not found
> ```


```
LABEL=cloudimg-rootfs	/	 ext4	discard,errors=remount-ro	0 1
LABEL=UEFI	/boot/efi	vfat	umask=0077	0 1
```
```
Filesystem      Size  Used Avail Use% Mounted on
tmpfs           391M  992K  390M   1% /run
/dev/sda1        20G  2.0G   18G  11% /
tmpfs           2.0G     0  2.0G   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
/dev/sda15      105M  6.1M   99M   6% /boot/efi
tmpfs           391M  4.0K  391M   1% /run/user/1001
```
Is there a better command ?

**Comment by naturedamends** [comment]
Arr, its an issue with the installation method https://snapcraft.io/docker.

Is this something the cli can support; changing the directory of the files which are created to all allow snaps default confinement to apply?

```
cat cloud-init.yml
users:
  - default
  - name: vmuser
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
    - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJi3WmihX63BYzsmFvBj1MsxkcSKGfIAgmOZfIJ6Ahf+ natured_amends0p@icloud.com
groups:
- docker
snap:
  commands:
  - [install, docker, --classic]
runcmd:
- adduser vmuser docker
- reboot
multipass launch --cloud-init ~/Desktop/cloud-init.yml --disk 20G --mem 4G --cpus 2 --name docker-vm
```

```
$ docker build -t test -f Dockerfile /tmp/empty 
unable to prepare context: path "/tmp/empty" not found
$ ls -la
total 56
drwxrwxrwt 13 root   root   4096 Sep  5 12:55 .
drwxr-xr-x 19 root   root   4096 Sep  5 12:50 ..
drwxrwxrwt  2 root   root   4096 Sep  5 12:50 .ICE-unix
drwxrwxrwt  2 root   root   4096 Sep  5 12:50 .Test-unix
drwxrwxrwt  2 root   root   4096 Sep  5 12:50 .X11-unix
drwxrwxrwt  2 root   root   4096 Sep  5 12:50 .XIM-unix
drwxrwxrwt  2 root   root   4096 Sep  5 12:50 .font-unix
-rw-rw-r--  1 vmuser vmuser   37 Sep  5 12:54 Dockerfile
drwxrwxr-x  2 vmuser vmuser 4096 Sep  5 12:54 empty
drwx------  4 root   root   4096 Sep  5 12:50 snap-private-tmp
drwx------  3 root   root   4096 Sep  5 12:50 systemd-private-47075d106ad14badabec6490ba3a7377-systemd-logind.service-XvM9Uj
drwx------  3 root   root   4096 Sep  5 12:50 systemd-private-47075d106ad14badabec6490ba3a7377-systemd-resolved.service-UoBuLX
drwx------  3 root   root   4096 Sep  5 12:55 systemd-private-47075d106ad14badabec6490ba3a7377-systemd-timedated.service-IEoDzJ
drwx------  3 root   root   4096 Sep  5 12:50 systemd-private-47075d106ad14badabec6490ba3a7377-systemd-timesyncd.service-lp7wrW
$ cat Dockerfile
FROM alpine
WORKDIR /app
RUN adfasdf
```

running in home directory does work

```
$ vim Dockerfile
$ mkdir empty
$ docker build -t test -f Dockerfile ./empty
Sending build context to Docker daemon  1.583kB
Step 1/2 : FROM alpine
latest: Pulling from library/alpine
7264a8db6415: Pull complete 
Digest: sha256:7144f7bab3d4c2648d7e59409f15ec52a18006a128c733fcff20d3a4a54ba44a
Status: Downloaded newer image for alpine:latest
 ---> 7e01a0d0a1dc
Step 2/2 : RUN asdfsd
 ---> Running in 489c581d9349
```

**Comment by naturedamends** [comment]
When inside the remote host, devcontainers extension will ask me to install docker

i'm getting the following output
```
 *  Executing task: chmod +x '/var/folders/9p/27z7ypt94t11m07t9yg46dlh0000gn/T/46886ac0-c53f-4d3e-95c7-6cf62ed471391693917975933-0.tmp.dmg' && open '/var/folders/9p/27z7ypt94t11m07t9yg46dlh0000gn/T/46886ac0-c53f-4d3e-95c7-6cf62ed471391693917975933-0.tmp.dmg' 


 *  The terminal process failed to launch: Starting directory (cwd) "/Users/dev" does not exist. 


```

Which seems like its trying to install a .dmg, but should it not be install docker for ubuntu, since i'm un a remote host

**Comment by chrmarti** [comment]
Similar issue in the extension repository: https://github.com/microsoft/vscode-remote-release/issues/5865
