### ISSUE TITLE
docker compose version doesn't have an option "--short"

### ISSUE THREAD

**Issue by hpe-ykoehler** [devcontainers/cli#650]
devcontainer CLI seems to detect the presence of docker-compose vs docker compose.  When using docker compose, it then call "docker compose version --short" but in version 20.10.21 common on Ubuntu 20.04 LTS systems the command then fails and return:

```
$ docker compose version --short
unknown flag: --short
See 'docker --help'.
```

Which from devcontainer output gives:

```
[2023-10-05T14:42:41.997Z] @devcontainers/cli 0.51.2. Node.js v18.18.0. linux 5.15.0-82-generic x64.
Error: Command failed: docker compose version --short
    at CI (.node/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:460:889)
    at async rtA (.node/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:611:22956)
    at async itA (.node/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:611:20283)
{"outcome":"error","message":"Command failed: docker compose version --short","description":"An error occurred retrieving the Docker Compose configuration."
```

If I install docker-compose it then pass.

**Comment by samruddhikhandale** [comment]
Hi 👋 

Can you try upgrading the docker version? Looks like you are using v20, and the latest is v24.

I was able to run `docker compose version --short` successfully with `Docker version 23.0.7`.

**Comment by hpe-ykoehler** [comment]
We try to use the software as made available to use by the distro, in this case Ubuntu 20.04 LTS, upgrading to latest is not always the best solution.

**Comment by mrequenes** [comment]
I'm running docker version 25.0.2 and `docker version --short` is not supported

**Comment by chrmarti** [comment]
Using compose v1 might be a workaround for early v2 versions that did not support `--short`. I will close this issue as hopefully  most systems have upgraded to more recent versions.

@mrequenes You mention `docker version`, but this is about `docker compose version`.
