### ISSUE TITLE
Devcontainer error

### ISSUE THREAD

**Issue by let4be** [devcontainers/cli#678]
```
2023-11-08 07:47:54.341Z: Creating container...
2023-11-08 07:47:54.410Z: $ devcontainer up --id-label Type=codespaces --workspace-folder /var/lib/docker/codespacemount/workspace/scrapfly-apps --mount type=bind,source=/.codespaces/agent/mount/cache,target=/vscode --user-data-folder /var/lib/docker/codespacemount/.persistedshare --container-data-folder .vscode-remote/data/Machine --container-system-data-folder /var/vscode-remote --log-level trace --log-format json --update-remote-user-uid-default never --mount-workspace-git-root false --omit-config-remote-env-from-metadata --skip-non-blocking-commands --skip-post-create --expect-existing-container --config "/var/lib/docker/codespacemount/workspace/scrapfly-apps/.devcontainer/devcontainer.json" --override-config /root/.codespaces/shared/merged_devcontainer.json --default-user-env-probe loginInteractiveShell --container-session-data-folder /workspaces/.codespaces/.persistedshare/devcontainers-cli/cache --secrets-file /root/.codespaces/shared/user-secrets-envs.json
2023-11-08 07:47:54.624Z: @devcontainers/cli 0.52.1. Node.js v18.17.1. linux 6.2.0-1015-azure x64.
2023-11-08 07:48:07.208Z: Shell server terminated (code: 137, signal: null)
2023-11-08 07:48:07.208Z: ␄
2023-11-08 07:48:07.209Z: {"outcome":"error","message":"An error occurred setting up the container.","description":"An error occurred setting up the container.","containerId":"9b0c4b8f597c25d51ebe7ab8d8bb64fa69a7ce7b8dd8b80a33619ae85ed731df"}
2023-11-08 07:48:07.210Z: Error: An error occurred setting up the container.
2023-11-08 07:48:07.211Z:     at EAA (/usr/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:462:1260)
2023-11-08 07:48:07.212Z:     at kK (/usr/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:462:1002)
2023-11-08 07:48:07.212Z:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-11-08 07:48:07.213Z:     at async NAA (/usr/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:479:3660)
2023-11-08 07:48:07.214Z:     at async vC (/usr/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:479:4775)
2023-11-08 07:48:07.215Z:     at async etA (/usr/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:613:10941)
2023-11-08 07:48:07.215Z:     at async AtA (/usr/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:613:10682)
2023-11-08 07:48:07.217Z: devcontainer process exited with exit code 1
```

**Comment by samruddhikhandale** [comment]
Looks like this was created by accident, closing. If needed, feel free to reopen with more details, thank you!
