### ISSUE TITLE
when opened devcontainer by `devcontainer open`, application insights error occured

### ISSUE THREAD

**Issue by curuknagao** [devcontainers/cli#706]
i got error like below, when i open devcontainer by cli.

```
ApplicationInsights:Failed to read JSON config file:  [
  Error: ENOENT: no such file or directory, open '/Users/knagao/.vscode/extensions/ms-vscode-remote.remote-containers-0.327.0/dev-containers-user-cli/applicationinsights.json'
      at Object.openSync (node:fs:603:3)
      at Object.func [as openSync] (node:electron/js2c/asar_bundle:2:1869)
      at Object.readFileSync (node:fs:471:35)
      at t.readFileSync (node:electron/js2c/asar_bundle:2:9212)
      at t._loadJsonFile (/Users/knagao/.vscode/extensions/ms-vscode-remote.remote-containers-0.327.0/dev-containers-user-cli/dist/node/devContainersUserCLI.js:32:5306)
      at new t (/Users/knagao/.vscode/extensions/ms-vscode-remote.remote-containers-0.327.0/dev-containers-user-cli/dist/node/devContainersUserCLI.js:32:4941)
      at t.getInstance (/Users/knagao/.vscode/extensions/ms-vscode-remote.remote-containers-0.327.0/dev-containers-user-cli/dist/node/devContainersUserCLI.js:32:5022)
      at /Users/knagao/.vscode/extensions/ms-vscode-remote.remote-containers-0.327.0/dev-containers-user-cli/dist/node/devContainersUserCLI.js:33:95718
      at /Users/knagao/.vscode/extensions/ms-vscode-remote.remote-containers-0.327.0/dev-containers-user-cli/dist/node/devContainersUserCLI.js:5:244
      at /Users/knagao/.vscode/extensions/ms-vscode-remote.remote-containers-0.327.0/dev-containers-user-cli/dist/node/devContainersUserCLI.js:38:32266 {
    errno: -2,
    syscall: 'open',
    code: 'ENOENT',
    path: '/Users/knagao/.vscode/extensions/ms-vscode-remote.remote-containers-0.327.0/dev-containers-user-cli/applicationinsights.json'
  }
]
ApplicationInsights:Invalid JSON config file:  [
  SyntaxError: Unexpected end of JSON input
      at JSON.parse (<anonymous>)
      at t._loadJsonFile (/Users/knagao/.vscode/extensions/ms-vscode-remote.remote-containers-0.327.0/dev-containers-user-cli/dist/node/devContainersUserCLI.js:32:5401)
      at new t (/Users/knagao/.vscode/extensions/ms-vscode-remote.remote-containers-0.327.0/dev-containers-user-cli/dist/node/devContainersUserCLI.js:32:4941)
      at t.getInstance (/Users/knagao/.vscode/extensions/ms-vscode-remote.remote-containers-0.327.0/dev-containers-user-cli/dist/node/devContainersUserCLI.js:32:5022)
      at /Users/knagao/.vscode/extensions/ms-vscode-remote.remote-containers-0.327.0/dev-containers-user-cli/dist/node/devContainersUserCLI.js:33:95718
      at /Users/knagao/.vscode/extensions/ms-vscode-remote.remote-containers-0.327.0/dev-containers-user-cli/dist/node/devContainersUserCLI.js:5:244
      at /Users/knagao/.vscode/extensions/ms-vscode-remote.remote-containers-0.327.0/dev-containers-user-cli/dist/node/devContainersUserCLI.js:38:32266
      at /Users/knagao/.vscode/extensions/ms-vscode-remote.remote-containers-0.327.0/dev-containers-user-cli/dist/node/devContainersUserCLI.js:5:244
      at /Users/knagao/.vscode/extensions/ms-vscode-remote.remote-containers-0.327.0/dev-containers-user-cli/dist/node/devContainersUserCLI.js:69:26198
      at /Users/knagao/.vscode/extensions/ms-vscode-remote.remote-containers-0.327.0/dev-containers-user-cli/dist/node/devContainersUserCLI.js:5:244
]
[138 ms] @devcontainers/cli 0.54.1. Node.js v18.15.0. darwin 22.4.0 arm64
```

**Comment by eljog** [comment]
Thank you for reporting this issue and sharing the detailed error message.
This appears to be an issue with the vscode remote extension. Could you please re-install the extension and try again?

If the problem persists please open and issue at https://github.com/microsoft/vscode-remote-release/issues repo.

**Comment by curuknagao** [comment]
thank you for reply.

i did
re-install devcontainer package, delete symbolic link for devcontainer-cli and re-install devcontainer cli

but, it didn't work for me.

i will open issue at https://github.com/microsoft/vscode-remote-release/issues

**Comment by jamesthurley** [comment]
@curuknagao I'm seeing the same issue. Did you resolve this, or open an issue in the other repo (I couldn't see it)?
