### ISSUE TITLE
devcontainer template publish does not support gcp artifact registry

### ISSUE THREAD

**Issue by yuhuyoyo** [devcontainers/cli#749]
SyntaxError: Unexpected token N in JSON at position 0
    at JSON.parse (<anonymous>)
    at jH (/opt/homebrew/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:602:773)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async qH (/opt/homebrew/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:600:654)
    at async JC (/opt/homebrew/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:604:1304)
    at async HeA (/opt/homebrew/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:604:5465)
    at async /opt/homebrew/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:604:4569

**Comment by samruddhikhandale** [comment]
Hi 👋 

Unfortunately, there is no current support for Google Cloud Platform's Artifact Registry. However, the CLI supports GitHub Container Registry and Azure Container Registry.

We'd be happy to add support for GCP given the community's interested. Feel free to contribute a PR if you'd be interested.
Thanks!
