### ISSUE TITLE
Devcontainer fails in open in windows but not on mac

### ISSUE THREAD

**Issue by ridhwaans** [devcontainers/cli#756]
crosspost from https://github.com/microsoft/vscode-remote-release/issues/9308

- VSCode Version: latest
- Local OS Version: windows 11 latest
- WSL version: WSL2 latest
- WSL2 Linux version: Ubuntu 22.04
- Extensions used - ms-vscode-remote.remote-containers (latest), ms-vscode-remote.remote-wsl (latest)
- environment - reopen in container from local window and within WSL2 window

- full container log:

```
[43 ms] Remote-Containers 0.245.2 in VS Code 1.67.2 (c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5).
[42 ms] Start: Run: wsl -d Ubuntu -e wslpath -u \\wsl.localhost\Ubuntu\home\ridhwaans\Source\devcontainer-features
[165 ms] Start: Resolving Remote
[182 ms] Start: Run: wsl -d Ubuntu -e wslpath -u \\wsl.localhost\Ubuntu\home\ridhwaans\Source\devcontainer-features
[305 ms] Start: Run: wsl -d Ubuntu -e /bin/sh -c cd '/home/ridhwaans/Source/devcontainer-features' && /bin/sh
[310 ms] Start: Run in host: id -un
[357 ms] ridhwaans
[357 ms] 
[357 ms] Start: Run in host: cat /etc/passwd
[360 ms] Start: Run in host: echo ~
[361 ms] /home/ridhwaans
[361 ms] 
[361 ms] Start: Run in host: test -x '/home/ridhwaans/.vscode-remote-containers/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/node'
[362 ms] 
[362 ms] 
[363 ms] Exit code 1
[363 ms] Start: Run in host: test -x '/home/ridhwaans/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/node'
[364 ms] 
[364 ms] 
[364 ms] Start: Run in host: test -f '/home/ridhwaans/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/node_modules/node-pty/package.json'
[365 ms] 
[365 ms] 
[365 ms] Start: Run in host: test -f '/home/ridhwaans/.vscode-remote-containers/dist/vscode-remote-containers-server-0.245.2.js'
[366 ms] 
[366 ms] 
[369 ms] userEnvProbe: loginInteractiveShell (default)
[369 ms] userEnvProbe shell: /usr/bin/zsh
[2384 ms] Start: Run in Host: /bin/sh 
[2387 ms] Start: Run in container: for pid in `cd /proc && ls -d [0-9]*`; do { echo $pid ; readlink /proc/$pid/cwd ; readlink /proc/$pid/ns/mnt ; cat /proc/$pid/stat | tr "
[2450 ms] userEnvProbe is taking longer than 2 seconds. Process tree:
  2033: /usr/bin/zsh -lic echo -n 1fc8b6dca1d79ac6927029bb6e998b20; cat /proc/self/environ; echo -n 1fc8b6dca1d79ac6927029bb6e998b20 
[3261 ms] userEnvProbe PATHs:
Probe:     '/home/ridhwaans/.pyenv/plugins/pyenv-virtualenv/shims:/home/ridhwaans/.pyenv/shims:/home/ridhwaans/.rbenv/shims:/home/ridhwaans/.sdkman/candidates/java/current/bin:/home/ridhwaans/.sdkman/candidates/gradle/current/bin:/home/ridhwaans/.nvm/versions/node/v20.0.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/wsl/lib:/mnt/c/Windows/system32:/mnt/c/Windows:/mnt/c/Windows/System32/Wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0/:/mnt/c/Windows/System32/OpenSSH/:/mnt/c/Program Files/NVIDIA Corporation/NVIDIA NvDLISR:/mnt/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/:/mnt/c/WINDOWS/System32/OpenSSH/:/mnt/c/Program Files/Microsoft/Web Platform Installer/:/mnt/c/Program Files/dotnet/:/mnt/c/Program Files/Microsoft SQL Server/150/Tools/Binn/:/mnt/c/Program Files/Microsoft SQL Server/Client SDK/ODBC/170/Tools/Binn/:/Docker/host/bin:/mnt/c/Users/shake/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/shake/AppData/Local/hyper/app-3.0.2/resources/bin:/mnt/c/Program Files/Microsoft VS Code/bin:/mnt/c/Users/shake/.dotnet/tools:/mnt/c/Program Files/Docker/Docker/resources/bin:/opt/homebrew/bin:/home/ridhwaans/.pyenv/bin:/home/ridhwaans/.rbenv/bin:/home/ridhwaans/bin:/home/ridhwaans/.local/bin:/usr/local/opt/openssl/bin:/usr/local/mysql/bin:/usr/local/go/bin:/home/ridhwaans/dotfiles/.zsh/bundle/bundles/robbyrussell/oh-my-zsh/lib'
Container: None
[3262 ms] Setting up container for folder or workspace: /home/ridhwaans/Source/devcontainer-features
[3263 ms] Start: Check Docker is running
[3264 ms] Start: Run in Host: docker version --format {{.Server.APIVersion}}
[3360 ms] Server API version: 1.41
[3360 ms] Start: Run in Host: docker volume ls -q
[3477 ms] Start: Run in Host: docker ps -q -a --filter label=vsch.local.folder=\\wsl.localhost\Ubuntu\home\ridhwaans\Source\devcontainer-features --filter label=vsch.quality=stable
[3633 ms] Start: Run in Host: docker ps -q -a --filter label=devcontainer.local_folder=\\wsl.localhost\Ubuntu\home\ridhwaans\Source\devcontainer-features
[3730 ms] Start: Run in Host: /home/ridhwaans/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/node /home/ridhwaans/.vscode-remote-containers/dist/dev-containers-cli-0.245.2/dist/spec-node/devContainersSpecCLI.js up --workspace-folder /home/ridhwaans/Source/devcontainer-features --workspace-mount-consistency cached --id-label devcontainer.local_folder=\\wsl.localhost\Ubuntu\home\ridhwaans\Source\devcontainer-features --log-level debug --log-format json --config /home/ridhwaans/Source/devcontainer-features/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[3835 ms] remote-containers 0.245.2.
[3835 ms] Start: Run: docker buildx version
[3972 ms] Start: Resolving Remote
[3974 ms] Start: Run: git rev-parse --show-cdup
[3978 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=\\wsl.localhost\Ubuntu\home\ridhwaans\Source\devcontainer-features
[4067 ms] local container features stored at: /home/ridhwaans/.vscode-remote-containers/dist/dev-containers-cli-0.245.2/dist/node_modules/vscode-dev-containers/container-features
[4068 ms] Start: Run: tar --no-same-owner -x -f -
[4109 ms] * Processing feature: ghcr.io/devcontainers/features/docker-in-docker:2
[4751 ms] * Fetching feature: docker-in-docker_1_oci
[5533 ms] Start: Run: docker inspect --type image mcr.microsoft.com/devcontainers/javascript-node
[5667 ms] Start: Run: docker buildx build --load --build-context dev_containers_feature_content_source=/tmp/vsch-ridhwaans/container-features/0.245.2-1708241120956 --build-arg _DEV_CONTAINERS_BASE_IMAGE=mcr.microsoft.com/devcontainers/javascript-node --build-arg _DEV_CONTAINERS_IMAGE_USER=root --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp --target dev_containers_target_stage -t vsc-devcontainer-features-371a2d39594520cab899c23907e2c2c1-features -f /tmp/vsch-ridhwaans/container-features/0.245.2-1708241120956/Dockerfile.extended /tmp/__dev-containers-build-empty
[+] Building 2.2s (13/13) FINISHED                                              
 => [internal] load build definition from Dockerfile.extended              0.1s
 => => transferring dockerfile: 524B                                       0.0s
 => [internal] load .dockerignore                                          0.1s
 => => transferring context: 2B                                            0.0s
 => resolve image config for docker.io/docker/dockerfile:1.4               1.5s
 => CACHED docker-image://docker.io/docker/dockerfile:1.4@sha256:9ba7531b  0.0s
 => [internal] load .dockerignore                                          0.0s
 => [internal] load build definition from Dockerfile.extended              0.0s
 => [context dev_containers_feature_content_source] load .dockerignore     0.0s
 => => transferring dev_containers_feature_content_source: 2B              0.0s
 => [internal] load metadata for mcr.microsoft.com/devcontainers/javascri  0.0s
 => [context dev_containers_feature_content_source] load from client       0.0s
 => => transferring dev_containers_feature_content_source: 34.89kB         0.0s
 => [dev_containers_target_stage 1/3] FROM mcr.microsoft.com/devcontainer  0.0s
 => CACHED [dev_containers_target_stage 2/3] COPY --from=dev_containers_f  0.0s
 => CACHED [dev_containers_target_stage 3/3] RUN cd /tmp/build-features/d  0.0s
 => exporting to image                                                     0.1s
 => => exporting layers                                                    0.0s
 => => writing image sha256:2744d0d6fa87b4735f83acdb5f64c94e4d090f38d2c40  0.0s
 => => naming to docker.io/library/vsc-devcontainer-features-371a2d395945  0.0s
[8664 ms] Start: Run: docker -v
[8719 ms] Start: Run: docker events --format {{json .}} --filter event=start
[8723 ms] Start: Starting container
[8723 ms] Start: Run: docker run --sig-proxy=false -a STDOUT -a STDERR --mount type=bind,source=/home/ridhwaans/Source/devcontainer-features,target=/workspaces/devcontainer-features --mount type=volume,src=dind-var-lib-docker-${devcontainerId},dst=/var/lib/docker --mount type=volume,src=vscode,dst=/vscode -l devcontainer.local_folder=\\wsl.localhost\Ubuntu\home\ridhwaans\Source\devcontainer-features --privileged --entrypoint /bin/sh vsc-devcontainer-features-371a2d39594520cab899c23907e2c2c1-features -c echo Container started
docker: Error response from daemon: create dind-var-lib-docker-${devcontainerId}: "dind-var-lib-docker-${devcontainerId}" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path.
See 'docker run --help'.
[8986 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=\\wsl.localhost\Ubuntu\home\ridhwaans\Source\devcontainer-features
[9064 ms] Error: Command failed: docker run --sig-proxy=false -a STDOUT -a STDERR --mount type=bind,source=/home/ridhwaans/Source/devcontainer-features,target=/workspaces/devcontainer-features --mount type=volume,src=dind-var-lib-docker-${devcontainerId},dst=/var/lib/docker --mount type=volume,src=vscode,dst=/vscode -l devcontainer.local_folder=\\wsl.localhost\Ubuntu\home\ridhwaans\Source\devcontainer-features --privileged --entrypoint /bin/sh vsc-devcontainer-features-371a2d39594520cab899c23907e2c2c1-features -c echo Container started
[9065 ms] trap "exit 0" 15
[9065 ms] /usr/local/share/docker-init.sh
[9065 ms] exec "$@"
[9065 ms] while sleep 1 & wait $!; do :; done -
[9065 ms]     at MS (/home/ridhwaans/.vscode-remote-containers/dist/dev-containers-cli-0.245.2/dist/spec-node/devContainersSpecCLI.js:255:2186)
[9065 ms]     at Zw (/home/ridhwaans/.vscode-remote-containers/dist/dev-containers-cli-0.245.2/dist/spec-node/devContainersSpecCLI.js:255:2124)
[9065 ms]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[9065 ms]     at async KS (/home/ridhwaans/.vscode-remote-containers/dist/dev-containers-cli-0.245.2/dist/spec-node/devContainersSpecCLI.js:261:2006)
[9065 ms]     at async co (/home/ridhwaans/.vscode-remote-containers/dist/dev-containers-cli-0.245.2/dist/spec-node/devContainersSpecCLI.js:261:3110)
[9066 ms]     at async LP (/home/ridhwaans/.vscode-remote-containers/dist/dev-containers-cli-0.245.2/dist/spec-node/devContainersSpecCLI.js:360:9352)
[9066 ms]     at async DP (/home/ridhwaans/.vscode-remote-containers/dist/dev-containers-cli-0.245.2/dist/spec-node/devContainersSpecCLI.js:360:9108)
[9068 ms] Exit code 1
[9071 ms] Command failed: /home/ridhwaans/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/node /home/ridhwaans/.vscode-remote-containers/dist/dev-containers-cli-0.245.2/dist/spec-node/devContainersSpecCLI.js up --workspace-folder /home/ridhwaans/Source/devcontainer-features --workspace-mount-consistency cached --id-label devcontainer.local_folder=\\wsl.localhost\Ubuntu\home\ridhwaans\Source\devcontainer-features --log-level debug --log-format json --config /home/ridhwaans/Source/devcontainer-features/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[9072 ms] Exit code 1
```
Steps to Reproduce:

1. Ubuntu is installed in WSL2 Windows 11
2. VSCode extensions [Remote containers](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-containers) and [WSL ](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-wsl)extensions are installed. Docker Desktop is already running on windows 11 (host machine) 
3. Repository containing `devcontainer.json` is cloned into WSL drive
4. In VSCode, open repository in a local window or "WSL" window
5. Command `Remote-Containers: Reopen in container`

This error doesn't happen with the VSCode remote container extension on MacOS

![Image](https://github.com/microsoft/vscode-remote-release/assets/1103336/54349370-7858-4bf6-953e-c0bbceae6cde)

![Image](https://github.com/devcontainers/cli/assets/1103336/5dfec785-d2e7-4efe-a4ff-72030c2a6e07)

Copy of `devcontainer.json` from error :
```
{
    "image": "mcr.microsoft.com/devcontainers/javascript-node",
    "features": {
        "ghcr.io/devcontainers/features/docker-in-docker:2": {}
    },
    "postCreateCommand": "npm install -g @devcontainers/cli",
    "hostRequirements": {
        "cpus": 4
    },
    "customizations": {
        "vscode": {
            "extensions": [
                "mads-hartmann.bash-ide-vscode"
            ]
        }
    }
  }
```

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by chrmarti** [comment]
Please append the full Dev Containers log from when this happens. (`F1` > `Dev Containers: Show Container Log`)

**Comment by ridhwaans** [comment]
I have made an edit with the full log. please check it out, thanks

**Comment by ridhwaans** [comment]
uninstalled vscode 1.67. Now installed vscode v1.87.2 and the issue is resolved. Closed
