### ISSUE TITLE
Error on devcontainer open on MacOS // vscode

### ISSUE THREAD

**Issue by spindev** [devcontainers/cli#760]
Hi there, I installed the DevContainers cli from vscode. If I want to start vscode with devcontainer open I'm getting the following error:

```shell
pplicationInsights:Failed to read JSON config file:  [
  Error: ENOENT: no such file or directory, open '/Users/tspindler/.vscode/extensions/ms-vscode-remote.remote-containers-0.338.1/dev-containers-user-cli/applicationinsights.json'
      at Object.openSync (node:fs:605:3)
      at Object.func [as openSync] (node:electron/js2c/asar_bundle:2:2131)
      at Object.readFileSync (node:fs:473:35)
      at Object.readFileSync (node:electron/js2c/asar_bundle:2:9462)
      at t._loadJsonFile (/Users/tspindler/.vscode/extensions/ms-vscode-remote.remote-containers-0.338.1/dev-containers-user-cli/dist/node/devContainersUserCLI.js:32:5306)
      at new t (/Users/tspindler/.vscode/extensions/ms-vscode-remote.remote-containers-0.338.1/dev-containers-user-cli/dist/node/devContainersUserCLI.js:32:4941)
      at t.getInstance (/Users/tspindler/.vscode/extensions/ms-vscode-remote.remote-containers-0.338.1/dev-containers-user-cli/dist/node/devContainersUserCLI.js:32:5022)
      at /Users/tspindler/.vscode/extensions/ms-vscode-remote.remote-containers-0.338.1/dev-containers-user-cli/dist/node/devContainersUserCLI.js:33:95718
      at /Users/tspindler/.vscode/extensions/ms-vscode-remote.remote-containers-0.338.1/dev-containers-user-cli/dist/node/devContainersUserCLI.js:5:244
      at /Users/tspindler/.vscode/extensions/ms-vscode-remote.remote-containers-0.338.1/dev-containers-user-cli/dist/node/devContainersUserCLI.js:38:32266 {
    errno: -2,
    syscall: 'open',
    code: 'ENOENT',
    path: '/Users/tspindler/.vscode/extensions/ms-vscode-remote.remote-containers-0.338.1/dev-containers-user-cli/applicationinsights.json'
  }
``` 

What is wrong here? The file is actually not available.

Thanks in advance :)

**Comment by spindev** [comment]
Duplicate. Sorry.
