### ISSUE TITLE
Issues following "Try out the CLI" instructions

### ISSUE THREAD

**Issue by BurtHarris** [devcontainers/cli#79]
Windows 11, Powershell Core 7.2.5, node v16.15.1
Note: node installed using nvm for windows version 1.1.9, if that matters

Following instructions in https://code.visualstudio.com/blogs/2022/05/18/dev-container-cli quite literally, I ran into some issues following the instructions referring to https://github.com/microsoft/vscode-remote-try-rust.  The instructions say:

```PowerShell
git clone https://github.com/microsoft/vscode-remote-try-rust
devcontainer up --workspace-folder <path-to-vscode-remote-try-rust>
```
Expected: these commands should execute without error.

Actual:  The first problem was the `<path-to-vscode-remote-try-rust>`, which isn't proper for any shell.   I replaced it with a relative path, so now I have:

```PowerShell
git clone https://github.com/microsoft/vscode-remote-try-rust
devcontainer up --workspace-folder ./vscode-remote-try-rust
``` 

So now I get an error I really don't understand:

```
Error: Command failed: docker ps -q -a --filter label=devcontainer.local_folder=C:\Users\burt_\vscode-remote-try-rust
    at createSetupError (C:\Users\burt_\AppData\Roaming\nvm\v16.15.1\node_modules\@devcontainers\cli\dist\spec-node\singleContainer.js:59:84)
    at openDockerfileDevContainer (C:\Users\burt_\AppData\Roaming\nvm\v16.15.1\node_modules\@devcontainers\cli\dist\spec-node\singleContainer.js:54:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async resolveWithLocalFolder (C:\Users\burt_\AppData\Roaming\nvm\v16.15.1\node_modules\@devcontainers\cli\dist\spec-node\configContainer.js:74:18)
    at async launch (C:\Users\burt_\AppData\Roaming\nvm\v16.15.1\node_modules\@devcontainers\cli\dist\spec-node\devContainers.js:42:20)
    at async doProvision (C:\Users\burt_\AppData\Roaming\nvm\v16.15.1\node_modules\@devcontainers\cli\dist\spec-node\devContainersSpecCLI.js:185:24)
    at async provision (C:\Users\burt_\AppData\Roaming\nvm\v16.15.1\node_modules\@devcontainers\cli\dist\spec-node\devContainersSpecCLI.js:170:20)
{"outcome":"error","message":"Command failed: docker ps -q -a --filter label=devcontainer.local_folder=C:\\Users\\burt_\\vscode-remote-try-rust","description":"An error occurred setting up the container."}
```

**Comment by chrmarti** [comment]
Could you rerun with `--log-level debug`.
